HEARTBEAT_NOT_RESPONDED_CODE = 3001
FROM_AGENT_MESSAGE_IS_NOT_VALID_JSON_CODE = 3002
FROM_AGENT_MESSAGE_DOES_NOT_MATCH_SCHEMA_CODE = 3003
FROM_AGENT_MESSAGE_RECEIVED_BEFORE_REGISTRATION_CODE = 3004
AGENT_IS_BLOCKED_CODE = 4003
AGENT_ALREADY_CONNECTED_CODE = 4004  # reject: another connection is already live and force was not set
AGENT_REPLACED_CODE = 4005  # incumbent connection kicked because a newer connection registered with force
