"""The typed port the real-time layer depends on (instead of the concrete singleton).

The DB is the source of truth; :class:`PersistBackend` describes the persistence seam the
transport-agnostic protocol code talks to, so the WebSocket consumer, the HTTP intake, and
the message router depend on an interface rather than on ``ModelPersistBackend`` directly.
(Outbound delivery is a small set of typed functions in :mod:`facade.transport`, not a
class, so it needs no Protocol here.)
"""

from __future__ import annotations

from typing import List, Optional, Protocol, Tuple, runtime_checkable

from facade import messages, models


@runtime_checkable
class PersistBackend(Protocol):
    """The DB-truth backend surface called by the transports (WS + HTTP intake).

    Every method persists/reads the authoritative Postgres rows. ``agent_id`` is the Agent
    pk (int); wire ids on ``messages`` are strings (the serialization boundary).
    """

    # --- connection lifecycle (executor + caller liveness) -------------------- #
    async def on_agent_connected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ...) -> List["models.Assignation"]: ...
    async def on_observer_connected(self, agent_id: int, connection_id: str | None = ..., mode: str | None = ...) -> List["models.Assignation"]: ...
    async def on_agent_disconnected(self, agent_id: int, connection_id: str | None = ...) -> None: ...
    async def on_caller_connected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ...) -> None: ...
    async def on_caller_disconnected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ..., mode: str | None = ...) -> None: ...

    async def get_or_create_caller_id(self, agent_id: int) -> str: ...

    # --- caller origination --------------------------------------------------- #
    async def on_caller_assign(
        self,
        agent_id: int,
        message: messages.CallerAssign,
        can_assign_root: bool,
        connection_id: str | None = ...,
        session_id: str | None = ...,
    ) -> Tuple["models.Assignation", bool]: ...

    # --- agent-reported events ------------------------------------------------ #
    async def on_agent_log(self, agent_id: int, message: messages.LogEvent) -> None: ...
    async def on_agent_yield(self, agent_id: int, message: messages.YieldEvent) -> None: ...
    async def on_agent_progress(self, agent_id: int, message: messages.ProgressEvent) -> None: ...
    async def on_agent_done(self, agent_id: int, message: messages.DoneEvent) -> None: ...
    async def on_agent_error(self, agent_id: int, message: messages.ErrorEvent) -> None: ...
    async def on_agent_critical(self, agent_id: int, message: messages.CriticalEvent) -> None: ...
    async def on_agent_cancelled(self, agent_id: int, message: messages.CancelledEvent) -> None: ...
    async def on_agent_state_patch(self, agent_id: int, message: messages.StatePatchEvent) -> None: ...
    async def on_agent_state_snapshot(self, agent_id: int, message: messages.StateSnapshotEvent) -> None: ...
    async def on_agent_session_init(self, agent_id: int, message: messages.SessionInitMessage) -> None: ...
