"""The typed port the real-time layer depends on (instead of the concrete singleton).

The DB is the source of truth; :class:`PersistBackend` describes the persistence seam the
transport-agnostic protocol code talks to, so the WebSocket consumer, the HTTP intake, and
the message router depend on an interface rather than on ``ModelPersistBackend`` directly.
(Outbound delivery is a small set of typed functions in :mod:`facade.transport`, not a
class, so it needs no Protocol here.)
"""

from __future__ import annotations

from typing import List, Optional, Protocol, Tuple, runtime_checkable

from facade import messages, models


@runtime_checkable
class PersistBackend(Protocol):
    """The DB-truth backend surface called by the transports (WS + HTTP intake).

    Every method persists/reads the authoritative Postgres rows. ``agent_id`` is the Agent
    pk (int); wire ids on ``messages`` are strings (the serialization boundary).
    """

    # --- connection lifecycle (executor + caller liveness) -------------------- #
    async def on_agent_connected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ...) -> List["models.Task"]: ...
    async def on_observer_connected(self, agent_id: int, connection_id: str | None = ..., mode: str | None = ...) -> List["models.Task"]: ...
    async def on_agent_disconnected(self, agent_id: int, connection_id: str | None = ...) -> None: ...
    async def on_caller_connected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ...) -> None: ...
    async def on_caller_disconnected(self, agent_id: int, connection_id: str | None = ..., session_id: str | None = ..., mode: str | None = ...) -> None: ...

    async def get_or_create_caller_id(self, agent_id: int) -> str: ...

    # --- caller origination --------------------------------------------------- #
    async def on_caller_assign(
        self,
        agent_id: int,
        message: messages.AssignRequest,
        can_assign_root: bool,
        connection_id: str | None = ...,
        session_id: str | None = ...,
    ) -> Tuple["models.Task", bool]: ...

    # --- caller lifecycle controls (request phase) ---------------------------- #
    async def on_caller_cancel(self, agent_id: int, message: messages.CancelRequest, *, connection_id: str | None = ..., session_id: str | None = ...) -> "models.Task": ...
    async def on_caller_interrupt(self, agent_id: int, message: messages.InterruptRequest, *, connection_id: str | None = ..., session_id: str | None = ...) -> "models.Task": ...
    async def on_caller_pause(self, agent_id: int, message: messages.PauseRequest, *, connection_id: str | None = ..., session_id: str | None = ...) -> "models.Task": ...
    async def on_caller_resume(self, agent_id: int, message: messages.ResumeRequest, *, connection_id: str | None = ..., session_id: str | None = ...) -> "models.Task": ...

    # --- lifecycle confirmations (confirm phase) ------------------------------ #
    async def on_agent_started(self, agent_id: int, message: messages.Started) -> None: ...
    async def on_agent_interrupted(self, agent_id: int, message: messages.Interrupted) -> None: ...
    async def on_agent_paused(self, agent_id: int, message: messages.Paused) -> None: ...
    async def on_agent_resumed(self, agent_id: int, message: messages.Resumed) -> None: ...

    # --- agent-reported events ------------------------------------------------ #
    async def on_agent_log(self, agent_id: int, message: messages.Log) -> None: ...
    async def on_agent_yield(self, agent_id: int, message: messages.Yield) -> None: ...
    async def on_agent_progress(self, agent_id: int, message: messages.Progress) -> None: ...
    async def on_agent_done(self, agent_id: int, message: messages.Completed) -> None: ...
    async def on_agent_error(self, agent_id: int, message: messages.Failed) -> None: ...
    async def on_agent_critical(self, agent_id: int, message: messages.Critical) -> None: ...
    async def on_agent_cancelled(self, agent_id: int, message: messages.Cancelled) -> None: ...
    async def on_agent_state_patch(self, agent_id: int, message: messages.StatePatch) -> None: ...
    async def on_agent_state_snapshot(self, agent_id: int, message: messages.StateSnapshot) -> None: ...
    async def on_agent_session_init(self, agent_id: int, message: messages.SessionInit) -> None: ...

    # --- distributed locks (acquire / release) -------------------------------- #
    async def on_agent_lock(self, agent_id: int, message: messages.Lock) -> None: ...
    async def on_agent_unlock(self, agent_id: int, message: messages.Unlock) -> None: ...
