"""GraphQL inputs for the facade app, split into domain submodules.

This ``__init__`` re-exports every public input (and its backing pydantic model) so
the established ``from facade import inputs`` / ``inputs.X`` access keeps working.
"""

from .agent import (
    BlockInput,
    BlockInputModel,
    BounceInput,
    BounceInputModel,
    KickInput,
    KickInputModel,
    PinInput,
    PinInputModel,
    UnblockInput,
    UnblockInputModel,
    UpdateAgentInput,
    UpdateAgentInputModel,
)
from .task import (
    AssignInput,
    AssignInputModel,
    CancelInput,
    CancelInputModel,
    CollectInput,
    CollectInputModel,
    HookInput,
    HookInputModel,
    InterruptInput,
    InterruptInputModel,
    PauseInput,
    PauseInputModel,
    ResumeInput,
    ResumeInputModel,
)
from .blok import (
    BlokAgentMappingInput,
    CreateBlokInput,
    CreateBlokInputModel,
    DeleteBlokInput,
    DeleteMaterializedBlokInput,
    MaterializeBlokInput,
    UpdateBlokInput,
    UpdateMaterializedBlokInput,
)
from .dashboard import (
    CreateDashboardInput,
    DeleteDashboardInput,
    UpdateDashboardInput,
)
from .dependency import (
    AutoResolveInput,
    CreateResolutionInput,
    CreateResolutionInputModel,
    DeleteResolutionInput,
    DeleteResolutionInputModel,
    MappedAgentInput,
    MappedAgentInputModel,
    ResolvedDependencyInput,
    ResolvedDependencyInputModel,
    UpdateResolutionInput,
    UpdateResolutionInputModel,
)
from .implementation import (
    ActionDemandInput,
    CreateImplementationInput,
    CreateImplementationInputModel,
    DeleteImplementationInput,
    DeleteImplementationInputModel,
    DescriptorInput,
    ObjectDemandInput,
    ObjectMatchInput,
    PortDemandInput,
    SchemaDemandInput,
)
from .state import (
    LogPatchesInput,
    LogPatchesInputModel,
    LogSnapshotInput,
    LogSnapshotInputModel,
    PatchInput,
    PatchInputModel,
)
from .threed import (
    CreatePlacementInput,
    CreatePlacementInputModel,
    CreateSpaceInput,
    CreateSpaceInputModel,
    CreateThreeDModelInput,
    CreateThreeDModelInputModel,
    DeletePlacementInput,
    DeletePlacementInputModel,
    DeleteSpaceInput,
    DeleteSpaceInputModel,
    DeleteThreeDModelInput,
    DeleteThreeDModelInputModel,
    PlacementInput,
    PlacementInputModel,
    UpdatePlacementInput,
    UpdatePlacementInputModel,
    UpdateSpaceInput,
    UpdateSpaceInputModel,
    UpdateThreeDModelInput,
    UpdateThreeDModelInputModel,
)
from .toolbox import (
    CreateShortcutInput,
    CreateShortcutInputModel,
    CreateToolboxInput,
    CreateToolboxInputModel,
    DeleteShortcutInput,
    DeleteShortcutInputModel,
    DeleteToolboxInput,
    DeleteToolboxInputModel,
)

__all__ = [
    # agent
    "BlockInput",
    "BlockInputModel",
    "BounceInput",
    "BounceInputModel",
    "KickInput",
    "KickInputModel",
    "PinInput",
    "PinInputModel",
    "UnblockInput",
    "UnblockInputModel",
    "UpdateAgentInput",
    "UpdateAgentInputModel",
    # task
    "AssignInput",
    "AssignInputModel",
    "CancelInput",
    "CancelInputModel",
    "CollectInput",
    "CollectInputModel",
    "HookInput",
    "HookInputModel",
    "InterruptInput",
    "InterruptInputModel",
    "PauseInput",
    "PauseInputModel",
    "ResumeInput",
    "ResumeInputModel",
    # blok
    "BlokAgentMappingInput",
    "CreateBlokInput",
    "CreateBlokInputModel",
    "DeleteBlokInput",
    "DeleteMaterializedBlokInput",
    "MaterializeBlokInput",
    "UpdateBlokInput",
    "UpdateMaterializedBlokInput",
    # dashboard
    "CreateDashboardInput",
    "DeleteDashboardInput",
    "UpdateDashboardInput",
    # dependency
    "AutoResolveInput",
    "CreateResolutionInput",
    "CreateResolutionInputModel",
    "DeleteResolutionInput",
    "DeleteResolutionInputModel",
    "MappedAgentInput",
    "MappedAgentInputModel",
    "ResolvedDependencyInput",
    "ResolvedDependencyInputModel",
    "UpdateResolutionInput",
    "UpdateResolutionInputModel",
    # implementation
    "ActionDemandInput",
    "DescriptorInput",
    "ObjectDemandInput",
    "ObjectMatchInput",
    "CreateImplementationInput",
    "CreateImplementationInputModel",
    "DeleteImplementationInput",
    "DeleteImplementationInputModel",
    "PortDemandInput",
    "SchemaDemandInput",
    # state
    "LogPatchesInput",
    "LogPatchesInputModel",
    "LogSnapshotInput",
    "LogSnapshotInputModel",
    "PatchInput",
    "PatchInputModel",
    # threed
    "CreatePlacementInput",
    "CreatePlacementInputModel",
    "CreateSpaceInput",
    "CreateSpaceInputModel",
    "CreateThreeDModelInput",
    "CreateThreeDModelInputModel",
    "DeletePlacementInput",
    "DeletePlacementInputModel",
    "DeleteSpaceInput",
    "DeleteSpaceInputModel",
    "DeleteThreeDModelInput",
    "DeleteThreeDModelInputModel",
    "PlacementInput",
    "PlacementInputModel",
    "UpdatePlacementInput",
    "UpdatePlacementInputModel",
    "UpdateSpaceInput",
    "UpdateSpaceInputModel",
    "UpdateThreeDModelInput",
    "UpdateThreeDModelInputModel",
    # toolbox
    "CreateShortcutInput",
    "CreateShortcutInputModel",
    "CreateToolboxInput",
    "CreateToolboxInputModel",
    "DeleteShortcutInput",
    "DeleteShortcutInputModel",
    "DeleteToolboxInput",
    "DeleteToolboxInputModel",
]
