# Generated by Django 4.2.4 on 2023-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="name",
        ),
        migrations.AddField(
            model_name="workspace",
            name="description",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="title",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
