# Generated by Django 4.2.4 on 2023-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0002_remove_workspace_name_workspace_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="name",
        ),
        migrations.AddField(
            model_name="flow",
            name="title",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
