# Generated by Django 4.2.4 on 2023-09-01 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0003_remove_flow_name_flow_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
