# Generated by Django 4.2.4 on 2023-09-02 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0004_flow_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactivetemplate",
            old_name="constream",
            new_name="constants",
        ),
        migrations.RenameField(
            model_name="reactivetemplate",
            old_name="instream",
            new_name="ins",
        ),
        migrations.RenameField(
            model_name="reactivetemplate",
            old_name="outstream",
            new_name="outs",
        ),
    ]
