# Generated by Django 4.2.4 on 2023-09-02 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0005_rename_constream_reactivetemplate_constants_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactivetemplate",
            old_name="name",
            new_name="title",
        ),
    ]
