# Generated by Django 4.2.4 on 2023-09-02 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0007_remove_reactivetemplate_defaults_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactivetemplate",
            old_name="kind",
            new_name="implementation",
        ),
    ]
