# Generated by Django 4.2.4 on 2023-09-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0007_node_defined_at_alter_provisionevent_provision"),
        ("reaktion", "0010_alter_run_assignation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trace",
            name="provision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trace",
                to="facade.provision",
            ),
        ),
    ]
