# Generated by Django 4.2.4 on 2023-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reaktion", "0011_alter_trace_provision"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactivetemplate",
            name="voids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
