"""
Django settings for kreature project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from .configuration import Settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.django.secret_key  # TODO: Change this in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AGENT_DISCONNECTED_TIMEOUT = 20
AGENT_HEARTBEAT_INTERVAL = 10
AGENT_HEARTBEAT_RESPONSE_TIMEOUT = 5

# Redis endpoint the agent queue (broadcast -> agent delivery) talks to.
AGENT_REDIS_HOST = conf.redis.host
AGENT_REDIS_PORT = conf.redis.port


AGENT_HEARTBEAT_NOT_RESPONDED_CODE = 3001

# Per-mode reclaim grace window (seconds). On a disconnect the failure/cascade is delayed
# this long so a brief blip can reclaim same-session in-flight work before it fires. 0 means
# no grace (strict). ``PHYSICAL`` overrides the window for effect:physical work, which may
# warrant a shorter (or zero) window than freely-retryable effect:none work. Consumed by the
# reclaim/grace backend via ``facade.grace.grace_seconds``.
REKUEST_GRACE = {
    "DEFAULT": conf.rekuest.grace_default,
    "PER_MODE": conf.rekuest.grace_per_mode,
    "PHYSICAL": conf.rekuest.grace_physical,
    # Progress lease (seconds): a physical task that has reported progress but then
    # goes silent this long — while its agent is still connected (wedged-but-alive) — is
    # failed as terminal. 0 disables the lease (default).
    "PROGRESS_LEASE": conf.rekuest.progress_lease,
}

# Capability scopes that gate ``AgentMode`` (see ``facade.capabilities``). Enforcement is
# opt-in so agents whose tokens predate these scopes keep working until ENFORCE is enabled.
REKUEST_CAPABILITIES = {
    "ENFORCE": conf.rekuest.enforce_capabilities,
    "EXECUTES_WORK_SCOPE": conf.rekuest.executes_work_scope,
    "CAN_ASSIGN_ROOT_SCOPE": conf.rekuest.can_assign_root_scope,
}

# Application definition
USE_X_FORWARDED_HOST = conf.django.use_x_forwarded_host


INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "guardian",
    "channels",
    "authentikate",
    "django_probes",
    "datalayer",
    "kante",
    "facade",
    "health_check",  # required
]

# Authentikate section

AUTH_USER_MODEL = "authentikate.User"

AUTHENTIKATE = conf.authentikate.model_dump()


# Provenance issuer section
#
# Rekuest mints a signed (Ed25519) provenance JWT at dispatch and publishes
# the verifying key at the JWKS endpoint (see ``rekuest/urls.py``). Loaded from the
# ``provenance`` block of config.yaml; a static ``provenance.private_key`` is
# required — the facade refuses to start without it (see facade/provenance/keys.py).
PROVENANCE = {
    "ISSUER": conf.provenance.issuer,
    "KID": conf.provenance.kid,
    "PRIVATE_KEY": conf.provenance.private_key,
    "PUBLIC_KEY": conf.provenance.public_key,
    "TOKEN_TTL_SECONDS": int(conf.provenance.token_ttl_seconds),
    "HUMAN_ROLES": list(conf.provenance.human_roles),
    "STRICT": bool(conf.provenance.strict),
}


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis chasnnel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": "mikro"},
    },
}

STRAWBERRY_DJANGO = {
    "USE_DEPRECATED_FILTERS": True,
    "DEFAULT_PK_FIELD_NAME": "id",
}


CSRF_TRUSTED_ORIGINS = conf.django.csrf_trusted_origins
MY_SCRIPT_NAME = conf.django.force_script_name


CORS_ALLOW_ALL_ORIGINS = True


DATALAYER = conf.datalayer.model_dump(exclude_none=True) if conf.datalayer else {}


ROOT_URLCONF = "rekuest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rekuest.wsgi.application"
ASGI_APPLICATION = "rekuest.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            # exact format is not important, this is the minimum information
            "format": "%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "rich.logging.RichHandler",
            "formatter": "console",
            "rich_tracebacks": True,
        },
    },
    "loggers": {
        # root logger
        "": {
            "level": "INFO",
            "handlers": ["console"],
        },
        "oauthlib": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "delt": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "oauth2_provider": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
