# Generated by Django 6.0.3 on 2026-04-07 13:54

import django.contrib.postgres.fields
import django.db.models.deletion
import django_choices_field.fields
import facade.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class ReservationStrategyChoices(models.TextChoices):
    """Historical enum for the removed Reservation model.

    The Reservation concept has been removed from the application, but this migration
    must remain self-contained so the historical schema can still be reconstructed.
    """

    RANDOM = "RANDOM", "Random"
    ROUND_ROBIN = "ROUND_ROBIN", "Round Robin"
    LEAST_BUSY = "LEAST_BUSY", "Least Busy"
    LEAST_TIME = "LEAST_TIME", "Least Time"
    LEAST_LOAD = "LEAST_LOAD", "Least Load"
    DIRECT = "DIRECT", "Direct"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('datalayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('ui_tree', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IconPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('default_widget', models.JSONField(blank=True, null=True)),
                ('default_return_widget', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Protocol', max_length=1000, unique=True)),
                ('description', models.TextField(help_text='A description for the Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='StateDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('hash', models.CharField(max_length=2000, unique=True)),
                ('ports', models.JSONField(default=dict)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StructurePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(help_text='A unique identifier for this action within the app', max_length=2000)),
                ('version', models.CharField(help_text='The version of this action (e.g. 1.0.0), this is used to differentiate if the underyling algorithm has changed, i.e we would expect different results for the same input', max_length=100)),
                ('pure', models.BooleanField(default=False, help_text='Is this function pure. e.g can we cache the result?')),
                ('idempotent', models.BooleanField(default=False, help_text='Is this function idempotent. e.g can we run it multiple times without changing the data again ?')),
                ('stateful', models.BooleanField(default=False, help_text='Is this function stateful. e.g does it inherently depend on or change state (think physical devices)?')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('FUNCTION', 'Function'), ('GENERATOR', 'Generator')], choices_enum=facade.enums.ActionKindChoices, default='FUNCTION', help_text='Function, generator? Will this function generate multiple results?', max_length=1000)),
                ('interfaces', models.JSONField(default=list, help_text='Interfaces that we use to interpret the meta data')),
                ('port_groups', models.JSONField(default=list, help_text='Intercae that we use to interpret the meta data')),
                ('name', models.CharField(default='Unnamed Action', help_text="The cleartext name of this Action (e.g. 'Segment Image')", max_length=1000)),
                ('description', models.TextField(help_text='A description for the Action')),
                ('scope', models.CharField(default='GLOBAL', help_text='The scope of this Action. e.g. does the data it needs or produce live only in the scope of this Action or is it global or does it bridge data?', max_length=1000)),
                ('is_dev', models.BooleanField(default=False, help_text='Is this Action a development Action')),
                ('hash', models.CharField(help_text='The hash of the Action (completely unique)', max_length=1000)),
                ('args', models.JSONField(default=list, help_text='Inputs for this Action')),
                ('returns', models.JSONField(default=list, help_text='Outputs for this Action')),
                ('arg_count', models.IntegerField(default=0, help_text='Pre-calculated number of root input ports')),
                ('return_count', models.IntegerField(default=0, help_text='Pre-calculated number of root output ports')),
                ('app', models.ForeignKey(help_text='The app this action belongs to (actions are part of an app and are NOT associated only with a release)', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='authentikate.app')),
                ('is_test_for', models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='tests', to='facade.action')),
                ('organization', models.ForeignKey(help_text='The organization this Action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that pinned this Actions', related_name='pinned_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('hash', models.CharField(help_text='The hash of the Agent (comparing the hash can be used to check if the agent has changed in a definition way)', max_length=1000)),
                ('name', models.CharField(default='Nana', help_text='This providers Name', max_length=2000)),
                ('extensions', models.JSONField(default=list, help_text='The extensions for this Agent', max_length=2000)),
                ('health_check_interval', models.IntegerField(default=300, help_text='How often should this agent be checked for its health. Defaults to 5 mins')),
                ('instance_id', models.CharField(default='main', max_length=1000)),
                ('unique', models.CharField(default=uuid.uuid4, help_text='The Channel we are listening to', max_length=1000)),
                ('on_instance', models.CharField(default='all', help_text='The Instance this Agent is running on', max_length=1000)),
                ('kind', models.CharField(choices=[(facade.enums.AgentKind['WEBSOCKET'], 'WEBSOCKET'), (facade.enums.AgentKind['WEBHOOK'], 'WEBHOOK')], default=facade.enums.AgentKind['WEBSOCKET'], help_text='The kind of this Agent', max_length=1000)),
                ('hook_url', models.CharField(blank=True, help_text='The webhook URL for this Agent (only if webhook)', max_length=1000, null=True)),
                ('hook_url_secret', models.CharField(blank=True, help_text='The webhook URL secret for this Agent (only if webhook)', max_length=1000, null=True)),
                ('latest_event', django_choices_field.fields.TextChoicesField(choices=[('DISCONNECT', 'Disconnect (Agent disconnected)'), ('CONNECT', 'Connect (Agent connected)')], choices_enum=facade.enums.AgentEventChoices, default='DISCONNECT', help_text='The Status of this Agent', max_length=1000)),
                ('connected', models.BooleanField(default=False, help_text='Is this Agent connected to the backend')),
                ('last_seen', models.DateTimeField(help_text='The last time this Agent was seen', null=True)),
                ('blocked', models.BooleanField(default=False, help_text='If this Agent is blocked, it will not be used for provision, nor will it be able to provide')),
                ('app', models.ForeignKey(help_text='The app this agent belongs to (agents are part of an app and are NOT associated only with a release)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.app')),
                ('device', models.ForeignKey(help_text='The device this agent belongs to (agents are part of a device and are NOT associated only with an app or release)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.device')),
                ('organization', models.ForeignKey(help_text='The organization this Agent belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that pinned this Agent', related_name='pinned_agents', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(help_text='The release this agent belongs to (agents are part of a release and are NOT associated only with an app)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.release')),
                ('user', models.ForeignKey(help_text='The user this Agent belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_provide_on', 'Can provide on this Agent')],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('DISCONNECT', 'Disconnect (Agent disconnected)'), ('CONNECT', 'Connect (Agent connected)')], choices_enum=facade.enums.AgentEventChoices, help_text='The event kind', max_length=1000)),
                ('level', django_choices_field.fields.TextChoicesField(blank=True, choices=[('DEBUG', 'DEBUG Level'), ('INFO', 'INFO Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level')], choices_enum=facade.enums.LogLevelChoices, help_text='The event level', max_length=1000, null=True)),
                ('agent', models.ForeignKey(help_text='The agent', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facade.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acted_on', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, help_text='Which structures were acted on in this assignation')),
                ('ephemeral', models.BooleanField(default=False, help_text='Is this Assignation ephemeral (e.g. should it be deleted after its done or should it be kept for future reference)')),
                ('hooks', models.JSONField(default=list, help_text='hooks that are tight to the lifecycle of this assignation')),
                ('reference', models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Assignation considering its parent', max_length=1000)),
                ('dependency', models.CharField(blank=True, default='general', help_text='The reference of the dependency this assignation was assigned to (e.g. imagej)', max_length=1000, null=True)),
                ('dependency_method', models.CharField(blank=True, help_text='The action of the dependency this assignation was assigned to (e.g. imagej.fft )', max_length=1000, null=True)),
                ('capture', models.BooleanField(default=False, help_text='Should we capture the logs and events of this Assignation (e.g. for debugging or auditing purposes)?')),
                ('args', models.JSONField(blank=True, default=dict, help_text='The Args', null=True)),
                ('dependencies', models.JSONField(blank=True, default=dict, help_text='The Args', null=True)),
                ('latest_event_kind', django_choices_field.fields.TextChoicesField(choices=[('QUEUED', 'Queued (Assignation was queued for a reservation)'), ('BOUND', 'Bound (Assignation was bound to an Agent)'), ('ASSIGN', 'Assign (Agent accepted the Assignation)'), ('UNASSIGN', 'Unassign (Agent received the Assignation)'), ('PROGRESS', 'Progress (Agent is making progress on the Assignation)'), ('CANCELING', 'Unassign (Assignation was unassigned from an Agent)'), ('CANCELLED', 'Unassign (Assignation was unassigned from an Agent)'), ('INTERUPTING', 'Interupting (Assignation was interupted)'), ('INTERUPTED', 'Interupted (Assignation was interupted)'), ('DELEGATE', 'Delegate (Assignation was delegated to another Assignation)'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('DISCONNECTED', 'Disconnected'), ('YIELD', 'Yields (Agent yielded the result)'), ('DONE', 'Done (Agent finished the Assignation)'), ('LOG', 'Log (Agent logged a message)')], choices_enum=facade.enums.TaskEventChoices, help_text='The latest Status of this Provision (transitioned by events)', max_length=1000)),
                ('latest_instruct_kind', django_choices_field.fields.TextChoicesField(choices=[('ASSIGN', 'Assign (Agent accepted the Assignation)'), ('CANCEL', 'Unassign (Agent received the Assignation)'), ('STEP', 'Step (Agent is making progress on the Assignation)'), ('RESUME', 'Resume (Agent resumed the Assignation)'), ('PAUSE', 'Pause (Agent paused the Assignation)'), ('INTERRUPT', 'Interrupt (Agent interupted the Assignation)'), ('COLLECT', 'Collect instruction received')], choices_enum=facade.enums.TaskInstructChoices, help_text='The latest Instruct of this Provision (transitioned by events)', max_length=1000)),
                ('statusmessage', models.CharField(blank=True, help_text='Clear Text status of the Provision as for now', max_length=1000)),
                ('is_done', models.BooleanField(default=False, help_text='Is this Assignation done (e.g. has it been completed and resulted in an error?)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='The action this was assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.action')),
                ('agent', models.ForeignKey(help_text='This Assignation app', max_length=1000, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.agent')),
                ('parent', models.ForeignKey(blank=True, help_text='The Assignations parent (the one that created this (none if there is no parent))', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.assignation')),
                ('root', models.ForeignKey(blank=True, help_text='The Root parent (the one that was created by the user (none if this is the root))', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_children', to='facade.assignation')),
            ],
        ),
        migrations.CreateModel(
            name='AssignationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returns', models.JSONField(blank=True, help_text='The returns of the events (true for yield events)', null=True)),
                ('progress', models.IntegerField(blank=True, help_text='The progress of the assignation (0-100) (set for yield events)', null=True)),
                ('message', models.CharField(blank=True, max_length=30000, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('QUEUED', 'Queued (Assignation was queued for a reservation)'), ('BOUND', 'Bound (Assignation was bound to an Agent)'), ('ASSIGN', 'Assign (Agent accepted the Assignation)'), ('UNASSIGN', 'Unassign (Agent received the Assignation)'), ('PROGRESS', 'Progress (Agent is making progress on the Assignation)'), ('CANCELING', 'Unassign (Assignation was unassigned from an Agent)'), ('CANCELLED', 'Unassign (Assignation was unassigned from an Agent)'), ('INTERUPTING', 'Interupting (Assignation was interupted)'), ('INTERUPTED', 'Interupted (Assignation was interupted)'), ('DELEGATE', 'Delegate (Assignation was delegated to another Assignation)'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('DISCONNECTED', 'Disconnected'), ('YIELD', 'Yields (Agent yielded the result)'), ('DONE', 'Done (Agent finished the Assignation)'), ('LOG', 'Log (Agent logged a message)')], choices_enum=facade.enums.TaskEventChoices, help_text='The event kind', max_length=1000)),
                ('level', django_choices_field.fields.TextChoicesField(blank=True, choices=[('QUEUED', 'Queued (Assignation was queued for a reservation)'), ('BOUND', 'Bound (Assignation was bound to an Agent)'), ('ASSIGN', 'Assign (Agent accepted the Assignation)'), ('UNASSIGN', 'Unassign (Agent received the Assignation)'), ('PROGRESS', 'Progress (Agent is making progress on the Assignation)'), ('CANCELING', 'Unassign (Assignation was unassigned from an Agent)'), ('CANCELLED', 'Unassign (Assignation was unassigned from an Agent)'), ('INTERUPTING', 'Interupting (Assignation was interupted)'), ('INTERUPTED', 'Interupted (Assignation was interupted)'), ('DELEGATE', 'Delegate (Assignation was delegated to another Assignation)'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('DISCONNECTED', 'Disconnected'), ('YIELD', 'Yields (Agent yielded the result)'), ('DONE', 'Done (Agent finished the Assignation)'), ('LOG', 'Log (Agent logged a message)')], choices_enum=facade.enums.TaskEventChoices, help_text='The log level', max_length=1000, null=True)),
                ('assignation', models.ForeignKey(help_text='The reservation this log item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facade.assignation')),
                ('delegated_to', models.ForeignKey(blank=True, help_text='If this event was delegated to another assignation, which one?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_events', to='facade.assignation')),
            ],
        ),
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_demands', models.JSONField(default=list, help_text='The action demands of this blok (e.g. the actions that this blok needs to run)')),
                ('state_demands', models.JSONField(default=list, help_text='The state demands of this blok (e.g. the states that this blok needs to run)')),
                ('url', models.CharField(blank=True, help_text='The URL of this Blok (e.g. the URL where this Blok is hosted)', max_length=1000, null=True)),
                ('creator', models.ForeignKey(help_text='The user that created this Blok', on_delete=django.db.models.deletion.CASCADE, related_name='bloks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_at', models.DateTimeField(auto_created=True, auto_now_add=True, help_text='Date this Collection was created')),
                ('name', models.CharField(help_text='The name of this Collection', max_length=1000, unique=True)),
                ('description', models.TextField(help_text='A description for the Collection')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date this Collection was last updated')),
                ('creator', models.ForeignKey(help_text='The user that created this Collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The Organization this Collection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='authentikate.organization')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='collections',
            field=models.ManyToManyField(help_text='The collections this Action belongs to', related_name='actions', to='facade.collection'),
        ),
        migrations.CreateModel(
            name='FilesystemShelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(default=uuid.uuid4, help_text='The Channel we are listening to', max_length=1000)),
                ('agents', models.ManyToManyField(help_text='The associated agent for this shelved item', related_name='filesystem_shelves', to='facade.agent')),
                ('creator', models.ForeignKey(help_text='The user that created this Shelf', on_delete=django.db.models.deletion.CASCADE, related_name='filesystem_shelves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(blank=True, help_text='The resource id of this drawer', max_length=1000, null=True)),
                ('identifier', models.CharField(help_text='The identifier of this drawer', max_length=1000)),
                ('label', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('shelve', models.ForeignKey(help_text='The associated shelve for this drawer', on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='facade.filesystemshelve')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_count', models.IntegerField(default=0)),
                ('cpu_vendor_name', models.CharField(default='Unknown', max_length=1000)),
                ('cpu_frequency', models.FloatField(default=0)),
                ('agent', models.ForeignKey(help_text='The associated agent for this HardwareRecord', on_delete=django.db.models.deletion.CASCADE, related_name='hardware_records', to='facade.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.CharField(max_length=10000)),
                ('hash', models.CharField(max_length=1000)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons', to='facade.action')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facade.iconpack')),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(help_text='Interface (think Function)', max_length=1000)),
                ('name', models.CharField(default='Unnamed', help_text='A name for this Implementation', max_length=1000)),
                ('extensions', models.JSONField(default=list, help_text='The attached extensions for this Implementation', max_length=2000)),
                ('policy', models.JSONField(default=dict, help_text='The attached policy for this implementation', max_length=2000)),
                ('extension', models.CharField(default='default', help_text='If this implementation is an extension of another implementation, this field links to the extension point (the implementation will actually get the params, the implementation and the args of this)', max_length=1000)),
                ('params', models.JSONField(default=dict, help_text='Params for this Implementation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic', models.BooleanField(help_text='Dynamic Implementations will be able to create new reservations on runtime')),
                ('action', models.ForeignKey(help_text='The action this implementation is implementatig', on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='facade.action')),
                ('agent', models.ForeignKey(help_text='The associated registry for this Implementation', on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='facade.agent')),
                ('higher_order_for', models.ForeignKey(blank=True, help_text='If this implementation is a higher order implementation, this field links to the lower order implementation it is wrapping (the implementation will actually get the params, the implementation and the args of this)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lower_order_implementations', to='facade.implementation')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that pinned this Agent', related_name='pinned_implementations', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(help_text='The release this implementation belongs to (implementations are part of a release and are NOT associated only with an app)', on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='authentikate.release')),
            ],
            options={
                'permissions': [('providable', 'Can provide this implementation')],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(help_text='A reference for this dependency', max_length=2000)),
                ('action_demands', models.JSONField(default=list, help_text='The action demands this dependency has to meet')),
                ('auto_resolvable', models.BooleanField(default=True, help_text='If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.')),
                ('app_filter', models.CharField(blank=True, help_text='If set, only Agents of this app will be able to be assigned to this dependency.', max_length=2000, null=True)),
                ('version_filter', models.CharField(blank=True, help_text='If set, only Agents of this version will be able to be assigned to this dependency', max_length=100, null=True)),
                ('optional', models.BooleanField(default=False, help_text='Is this dependency optional')),
                ('description', models.TextField(blank=True, help_text='A description for this dependency', null=True)),
                ('minimal_viable_instances', models.IntegerField(default=1, help_text='The minimal viable instance count for this dependency')),
                ('prefered_instances', models.IntegerField(default=1, help_text='The prefered instance count for this dependency')),
                ('assign_policy', models.CharField(choices=[(facade.enums.AssignPolicy['AUTOMATIC'], 'AUTOMATIC'), (facade.enums.AssignPolicy['ROUND_ROBIN'], 'ROUND_ROBIN'), (facade.enums.AssignPolicy['LEAST_BUSY'], 'LEAST_BUSY'), (facade.enums.AssignPolicy['FASTEST_RESPONSE'], 'FASTEST_RESPONSE')], default=facade.enums.AssignPolicy['AUTOMATIC'], help_text='The assign policy for this dependency', max_length=1000)),
                ('implementation', models.ForeignKey(help_text='The implementation that has this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='facade.implementation')),
            ],
        ),
        migrations.AddField(
            model_name='assignation',
            name='implementation',
            field=models.ForeignKey(blank=True, help_text='Which implementation is the assignation currently mapped (can be reassigned)?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.implementation'),
        ),
        migrations.CreateModel(
            name='InputInterfaceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.IntegerField(help_text='The index of the port this structure is used for')),
                ('port_key', models.CharField(help_text='The key of the port this structure is used for', max_length=2000)),
                ('modifiers', models.JSONField(default=list)),
                ('action', models.ForeignKey(help_text='The action this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='input_interface_usages', to='facade.action')),
                ('interface', models.ForeignKey(help_text='The structure this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='input_usages', to='facade.interface')),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(help_text='A unique identifier for this lock within the agent', max_length=2000)),
                ('description', models.TextField(help_text='A description for the Lock')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent this lock belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='facade.agent')),
                ('hold_by', models.ForeignKey(blank=True, help_text='The assigniation that currently holds this lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_locks', to='facade.assignation')),
            ],
        ),
        migrations.CreateModel(
            name='MaterializedBlok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Blok Implementation', max_length=1000)),
                ('description', models.TextField(help_text='A description for this Blok Implementation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.agent')),
                ('blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.blok')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key for this Action Mapping (e.g. the name of the action)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='facade.implementation')),
                ('materialized_blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='facade.materializedblok')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryShelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(help_text='The associated agent for this memory shelve', on_delete=django.db.models.deletion.CASCADE, related_name='memory_shelve', to='facade.agent')),
                ('creator', models.ForeignKey(help_text='The user that created this Shelf', on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(blank=True, help_text='The resource id of this drawer', max_length=1000, null=True)),
                ('identifier', models.CharField(help_text='The identifier of this drawer', max_length=1000)),
                ('label', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('shelve', models.ForeignKey(help_text='The associated shelve for this drawer', on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='facade.memoryshelve')),
            ],
        ),
        migrations.CreateModel(
            name='OutputInterfaceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.IntegerField(help_text='The index of the port this structure is used for')),
                ('port_key', models.CharField(help_text='The key of the port this structure is used for', max_length=2000)),
                ('modifiers', models.JSONField(default=list)),
                ('action', models.ForeignKey(help_text='The action this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='output_interface_usages', to='facade.action')),
                ('interface', models.ForeignKey(help_text='The interface this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='output_usages', to='facade.interface')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='protocols',
            field=models.ManyToManyField(blank=True, to='facade.protocol'),
        ),
        migrations.AddField(
            model_name='action',
            name='protocols',
            field=models.ManyToManyField(blank=True, help_text='The protocols this Action implements (e.g. Predicate)', related_name='actions', to='facade.protocol'),
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(help_text='The Associated Client', on_delete=django.db.models.deletion.CASCADE, to='authentikate.client')),
                ('organization', models.ForeignKey(help_text='The Organization this Registry belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('user', models.ForeignKey(help_text='The Associatsed User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='registry',
            field=models.ForeignKey(help_text='The provide might be limited to a instance like ImageJ belonging to a specific person. Is nullable for backend users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='facade.registry'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.UUIDField(default=uuid.uuid4, help_text='A Unique identifier for this Topic', unique=True)),
                ('saved_args', models.JSONField(default=dict)),
                ('strategy', django_choices_field.fields.TextChoicesField(choices=[('RANDOM', 'Random (Assignation is assigned to a random Provision)'), ('ROUND_ROBIN', 'Round Robin (Assignation is assigned to the next Provision)'), ('LEAST_BUSY', 'Least Busy (Assignation is assigned to the least busy Provision)'), ('LEAST_TIME', 'Least Time (Assignation is assigned to the Provision with the least time left)'), ('LEAST_LOAD', 'Least Load (Assignation is assigned to the Provision with the least load)'), ('DIRECT', 'Direct (Assignation is assigned to a direct Provision)')], choices_enum=ReservationStrategyChoices, default='RANDOM', help_text='The Strategy of this Reservation', max_length=1000)),
                ('allow_auto_request', models.BooleanField(default=False, help_text='Allow automatic requests for this reservation')),
                ('reference', models.CharField(blank=True, help_text='A Short Hand Way to identify this reservation for the creating app', max_length=200, null=True)),
                ('title', models.CharField(blank=True, help_text='A Short Hand Way to identify this reservation for you', max_length=200, null=True)),
                ('binds', models.JSONField(blank=True, help_text='Params for the Policy (including Agent etc..)', null=True)),
                ('statusmessage', models.CharField(blank=True, help_text='Clear Text status of the ssssssProvision as for now', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(help_text='The action this reservation connects', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.action')),
                ('causing_assignation', models.ForeignKey(blank=True, help_text='The assignation that created this reservation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_reservations', to='facade.assignation')),
                ('causing_dependency', models.ForeignKey(blank=True, help_text='Was this Reservation caused by a Dependency?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_reservations', to='facade.dependency')),
                ('implementations', models.ManyToManyField(help_text='The implementations this reservation connects', related_name='reservations', to='facade.implementation')),
            ],
        ),
        migrations.AddField(
            model_name='assignation',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Was this assigned through a reservation?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.reservation'),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, help_text="If set, this is a named preset (e.g. 'Standard Zeiss Config')", max_length=200, null=True)),
                ('is_template', models.BooleanField(default=False, help_text='If True, this resolution appears in search results for other users to reuse.')),
                ('creator', models.ForeignKey(help_text='The user that created this Resolution', on_delete=django.db.models.deletion.CASCADE, related_name='created_resolutions', to=settings.AUTH_USER_MODEL)),
                ('implementation', models.ForeignKey(help_text='The specific Implementation that this tree is configuring dependencies for.', on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='facade.implementation')),
                ('organization', models.ForeignKey(help_text='The organization this Resolution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='authentikate.organization')),
            ],
        ),
        migrations.AddField(
            model_name='assignation',
            name='resolution',
            field=models.ForeignKey(blank=True, help_text='The resolution used for this assignation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.resolution'),
        ),
        migrations.CreateModel(
            name='ResolvedDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000)),
                ('resolution_key', models.CharField(blank=True, help_text='An optional key to identify this resolution in the context of its parent resolution', max_length=2000, null=True)),
                ('dependency', models.ForeignKey(blank=True, help_text='The dependency this choice is fulfilling', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facade.dependency')),
                ('down_stream_resolution', models.ForeignKey(blank=True, help_text="The configuration tree for THIS implementation's dependencies", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='facade.resolution')),
                ('implementation', models.ForeignKey(help_text='The tool chosen to fulfill the dependency', on_delete=django.db.models.deletion.PROTECT, to='facade.implementation')),
                ('resolution', models.ForeignKey(help_text='The resolution scope this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_dependencies', to='facade.resolution')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The position of this port in the list')),
                ('key', models.CharField(help_text="The local key (e.g. 'mask')", max_length=255, null=True)),
                ('key_path', models.CharField(db_index=True, help_text="The full dot-notation path (e.g. 'options.advanced.mask')", max_length=500)),
                ('kind', models.CharField(help_text='The structural kind (e.g. LIST, DICT, INT)', max_length=50, null=True)),
                ('identifier', models.CharField(db_index=True, help_text="The macro-type (e.g. '@mikro/image')", max_length=255, null=True)),
                ('compiled_jsonpath', models.CharField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', max_length=1000, null=True)),
                ('nullable', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_ports', to='facade.action')),
                ('parent', models.ForeignKey(blank=True, help_text='If this port is nested inside a LIST or DICT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.returnport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='The unique identifier for this session', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time this session was last updated')),
                ('active', models.BooleanField(default=True, help_text='Is this session active?')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='facade.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='The user that created this Space', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this Space belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(help_text='The interface this state is for (e.g. Function)', max_length=1000)),
                ('value', models.JSONField(default=dict, help_text=' The current value of this state')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date this State was first ever written to')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date this State was last updated')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='facade.agent')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='facade.statedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='The value of this snapshot (e.g. the value of the state at the time of the snapshot)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time this snapshot was created')),
                ('global_rev', models.IntegerField(help_text='The revision of the state in the global context at the time of the snapshot (e.g. considering all patches that have been applied to this state)')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_created', to='facade.agent')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='facade.session')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='facade.state')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(help_text='The operation of this patch (e.g. add, remove, replace)', max_length=1000)),
                ('path', models.CharField(help_text='The path of this patch (e.g. the path to the value that is being changed)', max_length=1000)),
                ('value', models.JSONField(help_text='The value of this patch (e.g. the new value that is being set)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time this patch was created')),
                ('global_rev', models.IntegerField(help_text='The current revision of the state in the global context (e.g. considering all patches that have been applied to this state)')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches_created', to='facade.agent')),
                ('assignation', models.ForeignKey(blank=True, help_text='The assignation that caused this patch (e.g. to be able to track changes by assignation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.assignation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.session')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.state')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict, help_text=' The  value of this state atht he time of creation')),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='Date this State was archived')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_states', to='facade.state')),
            ],
        ),
        migrations.CreateModel(
            name='StateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key for this State Mapping (e.g. the name of the state)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materialized_blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='facade.materializedblok')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='facade.state')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique identifier for this structure', max_length=2000)),
                ('label', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('get_query', models.CharField(blank=True, max_length=2000, null=True)),
                ('describe_query', models.CharField(blank=True, max_length=2000, null=True)),
                ('default_widget', models.JSONField(blank=True, null=True)),
                ('default_return_widget', models.JSONField(blank=True, null=True)),
                ('descriptors', models.ManyToManyField(blank=True, to='facade.descriptor')),
                ('implements', models.ManyToManyField(blank=True, to='facade.interface')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='facade.structurepackage')),
            ],
        ),
        migrations.CreateModel(
            name='OutputStructureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.IntegerField(help_text='The index of the port this structure is used for')),
                ('port_key', models.CharField(help_text='The key of the port this structure is used for', max_length=2000)),
                ('modifiers', models.JSONField(default=list)),
                ('action', models.ForeignKey(help_text='The action this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='output_structure_usages', to='facade.action')),
                ('structure', models.ForeignKey(help_text='The structure this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='output_usages', to='facade.structure')),
            ],
        ),
        migrations.CreateModel(
            name='InputStructureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_index', models.IntegerField(help_text='The index of the port this structure is used for')),
                ('port_key', models.CharField(help_text='The key of the port this structure is used for', max_length=2000)),
                ('modifiers', models.JSONField(default=list)),
                ('action', models.ForeignKey(help_text='The action this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='input_structures_usages', to='facade.action')),
                ('structure', models.ForeignKey(help_text='The structure this usage is for', on_delete=django.db.models.deletion.CASCADE, related_name='input_usages', to='facade.structure')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.structure'),
        ),
        migrations.AddField(
            model_name='interface',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='facade.structurepackage'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='facade.structurepackage'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_benchmark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(help_text='The action this test belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='facade.action')),
                ('tester', models.ForeignKey(help_text='The action that is testing this test', on_delete=django.db.models.deletion.CASCADE, related_name='testing_cases', to='facade.action')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='facade.testcase')),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='facade.implementation')),
                ('tester', models.ForeignKey(help_text='The implementation that is testing this test', on_delete=django.db.models.deletion.CASCADE, related_name='testing_results', to='facade.implementation')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('transfer_function', models.CharField(help_text='The function used to transfer the state of the model to properties of the model', max_length=10000)),
                ('dependency', models.JSONField(blank=True, help_text='The protocol of the agent that we need to show this model', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(help_text='The media file containing this 3D model', on_delete=django.db.models.deletion.CASCADE, related_name='threedmodels', to='datalayer.mediastore')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(help_text='The role of this placement ', max_length=1000)),
                ('affine_matrix', models.JSONField(blank=True, help_text='The affine matrix of this placement (e.g. the position and orientation of the agent in the space)', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='facade.agent')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='facade.space')),
                ('model', models.ForeignKey(blank=True, help_text='An optional 3D model to represent this placement in a 3D space', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='facade.threedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Toolbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client this Toolbox belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes', to='authentikate.client')),
                ('creator', models.ForeignKey(help_text='The user that created this Shortcut', on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The Organization this Collection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('saved_args', models.JSONField(default=dict)),
                ('bind_number', models.IntegerField(blank=True, default=0, help_text='Which shortcut should be bound to this Action by default. 0 means no binding', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('args', models.JSONField(default=list, help_text='Inputs for this Shortcut')),
                ('returns', models.JSONField(default=list, help_text='Outputs for this Shortcut')),
                ('allow_quick', models.BooleanField(default=False, help_text='Allow quick execution of this Shortcut (e.g. run without confirmation)')),
                ('use_returns', models.BooleanField(default=False, help_text='Use the result of this Shortcut (e.g. use the result in the next Shortcut)')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='facade.action')),
                ('creator', models.ForeignKey(help_text='The user that created this Shortcut', on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL)),
                ('implementation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='facade.implementation')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='facade.toolbox')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(default='Nana', help_text='This waiters Name', max_length=2000)),
                ('instance_id', models.CharField(default='main', max_length=1000)),
                ('unique', models.CharField(default=uuid.uuid4, help_text='The Channel we are listening to', max_length=1000)),
                ('latest_event', django_choices_field.fields.TextChoicesField(choices=[('ACTIVE', 'Active'), ('KICKED', 'Just kicked'), ('DISCONNECTED', 'Disconnected'), ('VANILLA', 'Complete Vanilla Scenario after a forced restart of')], choices_enum=facade.enums.WaiterStatusChoices, default='VANILLA', help_text='The Status of this Waiter', max_length=1000)),
                ('registry', models.ForeignKey(help_text='The provide might be limited to a instance like ImageJ belonging to a specific person. Is nullable for backend users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='facade.registry')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='Which Waiter created this Reservation (if any?)', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facade.waiter'),
        ),
        migrations.CreateModel(
            name='AssignationInstruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('ASSIGN', 'Assign (Agent accepted the Assignation)'), ('CANCEL', 'Unassign (Agent received the Assignation)'), ('STEP', 'Step (Agent is making progress on the Assignation)'), ('RESUME', 'Resume (Agent resumed the Assignation)'), ('PAUSE', 'Pause (Agent paused the Assignation)'), ('INTERRUPT', 'Interrupt (Agent interupted the Assignation)'), ('COLLECT', 'Collect instruction received')], choices_enum=facade.enums.TaskInstructChoices, help_text='The event kind', max_length=1000)),
                ('assignation', models.ForeignKey(help_text='The reservation this log item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='instructs', to='facade.assignation')),
                ('waiter', models.ForeignKey(blank=True, help_text='Which Waiter created this Instruction (if any?)', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='facade.waiter')),
            ],
        ),
        migrations.AddField(
            model_name='assignation',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='This Assignation app', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.waiter'),
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('kind', models.CharField(max_length=2000)),
                ('hash', models.CharField(max_length=2000, unique=True)),
                ('values', models.JSONField(blank=True, null=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.structure')),
            ],
        ),
        migrations.CreateModel(
            name='ArgPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The position of this port in the list')),
                ('key', models.CharField(help_text="The local key (e.g. 'mask')", max_length=255, null=True)),
                ('key_path', models.CharField(db_index=True, help_text="The full dot-notation path (e.g. 'options.advanced.mask')", max_length=500)),
                ('kind', models.CharField(help_text='The structural kind (e.g. LIST, DICT, INT)', max_length=50, null=True)),
                ('identifier', models.CharField(db_index=True, help_text="The macro-type (e.g. '@mikro/image')", max_length=255, null=True)),
                ('compiled_jsonpath', models.CharField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', max_length=1000, null=True)),
                ('nullable', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arg_ports', to='facade.action')),
                ('parent', models.ForeignKey(blank=True, help_text='If this port is nested inside a LIST or DICT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.argport')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['action', 'key_path'], name='facade_argp_action__95bf79_idx'), models.Index(fields=['identifier'], name='facade_argp_identif_b280d7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='implementation',
            constraint=models.UniqueConstraint(fields=('interface', 'agent'), name='A implementation has unique reachable versions for every action it trys to implement'),
        ),
        migrations.AddConstraint(
            model_name='implementation',
            constraint=models.UniqueConstraint(fields=('action', 'agent'), name='An Agent can only have one implementation for the same Action'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('organization', 'app', 'key', 'version'), name='No multiple Actions with the same key and version in the same app for an organization allowed'),
        ),
        migrations.AddConstraint(
            model_name='registry',
            constraint=models.UniqueConstraint(fields=('client', 'user', 'organization'), name='No multiple Registries for same App and User in the same organization allowed'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('registry', 'instance_id'), name='No multiple Agents for same App and User allowed on same identifier'),
        ),
        migrations.AddIndex(
            model_name='returnport',
            index=models.Index(fields=['action', 'key_path'], name='facade_retu_action__8a4c86_idx'),
        ),
        migrations.AddIndex(
            model_name='returnport',
            index=models.Index(fields=['identifier'], name='facade_retu_identif_3e34f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('interface', 'agent'), name='No multiple States for same Agent and Schema allowed'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('package', 'key'), name='No multiple Structures with same key in the same package allowed'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('package', 'key'), name='No multiple Interfaces with same key in the same package allowed'),
        ),
        migrations.AddConstraint(
            model_name='descriptor',
            constraint=models.UniqueConstraint(fields=('package', 'key'), name='No multiple Descriptors with same key in the same package allowed'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('action', 'tester'), name='No multiple Tests for same Action and Tester allowed'),
        ),
        migrations.AddConstraint(
            model_name='waiter',
            constraint=models.UniqueConstraint(fields=('registry', 'instance_id'), name='No multiple Waiters for same App and User allowed on same instance_id'),
        ),
    ]
