# Generated by Django 6.0.3 on 2026-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=1, help_text='The unique identifier for this session', max_length=1000),
            preserve_default=False,
        ),
    ]
