# Generated by Django 5.2 on 2026-03-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='app',
            field=models.ForeignKey(default=1, help_text='The app this agent belongs to (agents are part of an app and are NOT associated only with a release)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.app'),
            preserve_default=False,
        ),
    ]
