# Generated by Django 4.2.4 on 2024-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="binds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The binds for this dependency (Determines which templates can be used for this dependency)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="A reference for this dependency",
                max_length=2000,
                null=True,
            ),
        ),
    ]
