# Generated by Django 5.2 on 2025-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='description',
            field=models.TextField(blank=True, help_text='An optional description for this dependency', null=True),
        ),
    ]
