# Generated by Django 4.2.4 on 2025-04-13 15:34

from django.db import migrations
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignation",
            old_name="status",
            new_name="latest_event_kind",
        ),
        migrations.AddField(
            model_name="assignation",
            name="latest_instruct_kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ASSIGN", "Assign (Agent accepted the Assignation)"),
                    ("CANCEL", "Unassign (Agent received the Assignation)"),
                    ("STEP", "Step (Agent is making progress on the Assignation)"),
                    ("RESUME", "Resume (Agent resumed the Assignation)"),
                    ("PAUSE", "Pause (Agent paused the Assignation)"),
                    ("INTERRUPT", "Interrupt (Agent interupted the Assignation)"),
                    ("COLLECT", "Collect instruction received"),
                ],
                choices_enum=facade.enums.AssignationInstructChoices,
                default="ASSIGN",
                help_text="The latest Instruct of this Provision (transitioned by events)",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
