# Generated by Django 4.2.4 on 2025-05-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelvedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drawer_id",
                    models.CharField(
                        help_text="The drawer this shelved item belongs to",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The identifier of this shelved item ",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of this shelved item",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The associated agent for this shelved item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelved_items",
                        to="facade.agent",
                    ),
                ),
            ],
        ),
    ]
