# Generated by Django 6.0.3 on 2026-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argport',
            name='dimension',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical pint dimensionality for QUANTITY ports (the wiring-compatibility key)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnport',
            name='dimension',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical pint dimensionality for QUANTITY ports (the wiring-compatibility key)', max_length=255, null=True),
        ),
    ]
