# Generated by Django 5.2 on 2025-06-12 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='panels',
        ),
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_demands', models.JSONField(default=list, help_text='The action demands of this blok (e.g. the actions that this blok needs to run)')),
                ('state_demands', models.JSONField(default=list, help_text='The state demands of this blok (e.g. the states that this blok needs to run)')),
                ('url', models.CharField(blank=True, help_text='The URL of this Blok (e.g. the URL where this Blok is hosted)', max_length=1000, null=True)),
                ('creator', models.ForeignKey(help_text='The user that created this Blok', on_delete=django.db.models.deletion.CASCADE, related_name='bloks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterializedBlok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this Blok Implementation', max_length=1000)),
                ('description', models.TextField(help_text='A description for this Blok Implementation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.agent')),
                ('blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materializations', to='facade.blok')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key for this Action Mapping (e.g. the name of the action)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='facade.implementation')),
                ('materialized_blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='facade.materializedblok')),
            ],
        ),
        migrations.CreateModel(
            name='StateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key for this State Mapping (e.g. the name of the state)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materialized_blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='facade.materializedblok')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='facade.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
    ]
