# Generated by Django 5.2 on 2025-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='bind_number',
            field=models.IntegerField(blank=True, default=0, help_text='Which shortcut should be bound to this Action by default. 0 means no binding', null=True),
        ),
    ]
