# Generated by Django 5.2 on 2025-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_dependency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='dependencies',
            field=models.JSONField(blank=True, default=dict, help_text='The Args', null=True),
        ),
    ]
