# Generated by Django 4.2.4 on 2025-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0002_rename_status_assignation_latest_event_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignation",
            name="is_done",
            field=models.BooleanField(
                default=False,
                help_text="Is this Assignation done (e.g. has it been completed and resulted in an error?)",
            ),
        ),
    ]
