# Generated by Django 5.2 on 2025-08-18 19:09

import facade.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_shortcut_bind_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hook_url',
            field=models.CharField(blank=True, help_text='The webhook URL for this Agent (only if webhook)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='hook_url_secret',
            field=models.CharField(blank=True, help_text='The webhook URL secret for this Agent (only if webhook)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kind',
            field=models.CharField(choices=[(facade.enums.AgentKind['WEBSOCKET'], 'WEBSOCKET'), (facade.enums.AgentKind['WEBHOOK'], 'WEBHOOK')], default=facade.enums.AgentKind['WEBSOCKET'], help_text='The kind of this Agent', max_length=1000),
        ),
    ]
