# Generated by Django 5.2 on 2026-03-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0002_agent_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(default=1, help_text='The organization this Agent belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
            preserve_default=False,
        ),
    ]
