# Generated by Django 4.2.4 on 2024-10-04 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facade", "0002_rename_state_hash_stateschema_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that pinned this Agent",
                related_name="pinned_agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that pinned this Nodes",
                related_name="pinned_nodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that pinned this Agent",
                related_name="pinned_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
