# Generated by Django 4.2.4 on 2023-08-04 15:06

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import facade.enums
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0002_provision_waiter_reservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="The Unique identifier of this Assignation considering its parent",
                        max_length=1000,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True, default=list, help_text="The Args", null=True
                    ),
                ),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("BOUND", "Bound (Assignation was bound to an Agent)"),
                            ("ASSIGN", "Assign (Agent accepted the Assignation)"),
                            ("UNASSIGN", "Unassign (Agent received the Assignation)"),
                            (
                                "PROGRESS",
                                "Progress (Agent is making progress on the Assignation)",
                            ),
                            ("YIELD", "Yields (Agent yielded the result)"),
                            ("DONE", "Done (Agent finished the Assignation)"),
                            ("LOG_INFO", "Log Info"),
                            ("LOG_WARN", "Log Warn"),
                            ("LOG_ERROR", "Log Error"),
                            ("LOG_DEBUG", "Log Debug"),
                            ("LOG_CRITICAL", "Log Critical"),
                        ],
                        choices_enum=facade.enums.AssignationEventChoices,
                        help_text="The Status of this Provision (transitioned by events)",
                        max_length=1000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Assignations parent (the one that created this)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="facade.assignation",
                    ),
                ),
                (
                    "provision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which Provision did we end up being assigned to (will change after a bound)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations",
                        to="facade.provision",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which reservation are we assigning to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations",
                        to="facade.reservation",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        blank=True,
                        help_text="This Assignation app",
                        max_length=1000,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignations",
                        to="facade.waiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=2000, null=True)),
                ("name", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("is_benchmark", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        help_text="The node this test belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="facade.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("result", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="facade.testcase",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testresults",
                        to="facade.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "returns",
                    models.JSONField(
                        blank=True, help_text="The return of the assignation", null=True
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(help_text="The progress of the assignation"),
                ),
                ("message", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("BOUND", "Bound (Assignation was bound to an Agent)"),
                            ("ASSIGN", "Assign (Agent accepted the Assignation)"),
                            ("UNASSIGN", "Unassign (Agent received the Assignation)"),
                            (
                                "PROGRESS",
                                "Progress (Agent is making progress on the Assignation)",
                            ),
                            ("YIELD", "Yields (Agent yielded the result)"),
                            ("DONE", "Done (Agent finished the Assignation)"),
                            ("LOG_INFO", "Log Info"),
                            ("LOG_WARN", "Log Warn"),
                            ("LOG_ERROR", "Log Error"),
                            ("LOG_DEBUG", "Log Debug"),
                            ("LOG_CRITICAL", "Log Critical"),
                        ],
                        choices_enum=facade.enums.AssignationEventChoices,
                        help_text="The event kind",
                        max_length=1000,
                    ),
                ),
                (
                    "assignation",
                    models.ForeignKey(
                        help_text="The reservation this log item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="facade.assignation",
                    ),
                ),
            ],
        ),
    ]
