# Generated by Django 6.0.3 on 2026-07-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_argport_dimension_returnport_dimension'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='argport',
            name='facade_argp_identif_b280d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnport',
            name='facade_retu_identif_3e34f8_idx',
        ),
        migrations.AddIndex(
            model_name='argport',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['action', 'kind'], name='argport_root_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='argport',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['action', 'nullable'], name='argport_root_null_idx'),
        ),
        migrations.AddIndex(
            model_name='returnport',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['action', 'kind'], name='returnport_root_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='returnport',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['action', 'nullable'], name='returnport_root_null_idx'),
        ),
    ]
