# Generated by Django 5.2 on 2025-06-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_remove_dashboard_panels_blok_materializedblok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materializedblok',
            name='blok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_bloks', to='facade.blok'),
        ),
    ]
