# Generated by Django 4.2.4 on 2025-05-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facade", "0002_shelveditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDrawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="The resource id of this drawer",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The identifier of this drawer", max_length=1000
                    ),
                ),
                ("label", models.CharField(max_length=1000, null=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FilesystemShelve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="The Channel we are listening to",
                        max_length=1000,
                    ),
                ),
                (
                    "agents",
                    models.ManyToManyField(
                        help_text="The associated agent for this shelved item",
                        related_name="filesystem_shelves",
                        to="facade.agent",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user that created this Shelf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filesystem_shelves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoryDrawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="The resource id of this drawer",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The identifier of this drawer", max_length=1000
                    ),
                ),
                ("label", models.CharField(max_length=1000, null=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemoryShelve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="The resource id of this shelve",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The associated agent for this shelved item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="facade.agent",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user that created this Shelf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ShelvedItem",
        ),
        migrations.AddField(
            model_name="memorydrawer",
            name="shelve",
            field=models.ForeignKey(
                help_text="The associated shelve for this drawer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawers",
                to="facade.memoryshelve",
            ),
        ),
        migrations.AddField(
            model_name="filedrawer",
            name="shelve",
            field=models.ForeignKey(
                help_text="The associated shelve for this drawer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawers",
                to="facade.filesystemshelve",
            ),
        ),
    ]
