# Generated by Django 4.2.4 on 2025-05-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0003_filedrawer_filesystemshelve_memorydrawer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memoryshelve",
            name="resource_id",
        ),
        migrations.AlterField(
            model_name="memoryshelve",
            name="agent",
            field=models.OneToOneField(
                help_text="The associated agent for this memory shelve",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_shelve",
                to="facade.agent",
            ),
        ),
    ]
