# Generated by Django 5.2 on 2025-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_agent_hook_url_agent_hook_url_secret_agent_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='initial_hash',
            new_name='action_hash',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='action',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='binds',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='reference',
        ),
        migrations.AddField(
            model_name='dependency',
            name='arg_matches',
            field=models.JSONField(blank=True, default=list, help_text='The binds for this dependency (Determines which implementations can be used for this dependency)', null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='key',
            field=models.CharField(default=1, help_text='A reference for this dependency', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='return_matches',
            field=models.JSONField(blank=True, default=list, help_text='The binds for this dependency (Determines which implementations can be used for this dependency)', null=True),
        ),
    ]
