# Generated by Django 6.0.3 on 2026-07-02 09:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_remove_argport_facade_argp_identif_b280d7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputinterfaceusage',
            name='action',
        ),
        migrations.RemoveField(
            model_name='inputinterfaceusage',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='inputstructureusage',
            name='action',
        ),
        migrations.RemoveField(
            model_name='inputstructureusage',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='outputinterfaceusage',
            name='action',
        ),
        migrations.RemoveField(
            model_name='outputinterfaceusage',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='outputstructureusage',
            name='action',
        ),
        migrations.RemoveField(
            model_name='outputstructureusage',
            name='structure',
        ),
        migrations.AddIndex(
            model_name='argport',
            index=models.Index(django.db.models.functions.text.Upper('identifier'), name='argport_ident_upper_idx'),
        ),
        migrations.AddIndex(
            model_name='returnport',
            index=models.Index(django.db.models.functions.text.Upper('identifier'), name='returnport_ident_upper_idx'),
        ),
        migrations.DeleteModel(
            name='InputInterfaceUsage',
        ),
        migrations.DeleteModel(
            name='InputStructureUsage',
        ),
        migrations.DeleteModel(
            name='OutputInterfaceUsage',
        ),
        migrations.DeleteModel(
            name='OutputStructureUsage',
        ),
    ]
