# Generated by Django 5.2 on 2025-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_assignation_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='describe_query',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='get_query',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
