# Generated by Django 4.2.4 on 2023-08-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0003_assignation_testcase_testresult_assignationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignation",
            name="statusmessage",
            field=models.CharField(
                blank=True,
                help_text="Clear Text status of the Provision as for now",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="assignationevent",
            name="assignation",
            field=models.ForeignKey(
                help_text="The reservation this log item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="facade.assignation",
            ),
        ),
    ]
