# Generated by Django 4.2.4 on 2024-08-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0003_structure_stateschema_state_dashboard_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="data",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="state",
            name="agent",
        ),
        migrations.AlterField(
            model_name="state",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="facade.stateschema",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_states",
                        to="facade.state",
                    ),
                ),
            ],
        ),
    ]
