# Generated by Django 5.2 on 2025-06-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0001_initial'),
        ('facade', '0003_alter_materializedblok_blok'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='client',
            field=models.ForeignKey(default=1, help_text='The client this Toolbox belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='toolboxes', to='authentikate.client'),
            preserve_default=False,
        ),
    ]
