# Generated by Django 5.2 on 2026-03-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0004_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='release',
            field=models.ForeignKey(default=1, help_text='The release this implementation belongs to (implementations are part of a release and are NOT associated only with an app)', on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='authentikate.release'),
            preserve_default=False,
        ),
    ]
