# Generated by Django 5.2 on 2025-11-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_structure_describe_query_structure_get_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='catpure',
            field=models.BooleanField(default=False, help_text='Should we capture the logs and events of this Assignation (e.g. for debugging or auditing purposes)?'),
        ),
    ]
