# Generated by Django 6.0.3 on 2026-07-02 10:25

from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery


def backfill_state_identity(apps, schema_editor):
    """Existing states get the registration defaults: key = interface, app = agent's app."""
    State = apps.get_model("facade", "State")
    Agent = apps.get_model("facade", "Agent")
    State.objects.filter(key__isnull=True).update(key=F("interface"))
    State.objects.filter(app_identifier__isnull=True).update(app_identifier=Subquery(Agent.objects.filter(pk=OuterRef("agent_id")).values("app__identifier")[:1]))


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_remove_inputinterfaceusage_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='app_identifier',
            field=models.CharField(blank=True, help_text="The identifier of the app providing this state (defaults to the owning agent's app identifier at registration)", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='key',
            field=models.CharField(blank=True, help_text='The stable identity key of this state, matched by state demands (defaults to the interface at registration)', max_length=1000, null=True),
        ),
        migrations.RunPython(backfill_state_identity, migrations.RunPython.noop),
    ]
