# Generated by Django 4.2.4 on 2023-08-31 14:45

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0004_assignation_statusmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("CHANGE", "Change (Reservation changed its status)"),
                            ("LOG", "Log (Reservation logged a message)"),
                        ],
                        choices_enum=facade.enums.ReservationEventChoices,
                        help_text="The event kind",
                        max_length=1000,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        help_text="The reservation this log item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="facade.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvisionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("CHANGE", "Change (Provision changed its status)"),
                            ("LOG", "Log (Provision logged a message)"),
                        ],
                        choices_enum=facade.enums.ProvisionEventChoices,
                        help_text="The event kind",
                        max_length=1000,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        help_text="The reservation this log item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="facade.provision",
                    ),
                ),
            ],
        ),
    ]
