# Generated by Django 5.2 on 2025-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_rename_initial_hash_dependency_action_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='protocols',
            field=models.JSONField(default=list, help_text='The protocols this dependency needs to match'),
        ),
    ]
