# Generated by Django 4.2.4 on 2024-08-21 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0004_rename_data_state_value_remove_state_agent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="schema",
            new_name="state_schema",
        ),
    ]
