# Generated by Django 6.0.3 on 2026-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_alter_dependency_max_viable_instances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='manipulates',
            field=models.ManyToManyField(help_text='Which states does this implementation manipulate?', related_name='manipulated_by', to='facade.state'),
        ),
        migrations.AddField(
            model_name='implementation',
            name='tracks',
            field=models.JSONField(default=list, help_text='A log of all the assignations that have been provisioned with this implementation, as well as their status and results'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='auto_resolvable',
            field=models.BooleanField(default=False, help_text='If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.'),
        ),
    ]
