# Generated by Django 4.2.4 on 2023-08-31 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0005_reservationevent_provisionevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provisionevent",
            old_name="reservation",
            new_name="provision",
        ),
    ]
