# Generated by Django 5.2 on 2026-03-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0005_implementation_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='release',
            field=models.ForeignKey(default=1, help_text='The release this agent belongs to (agents are part of a release and are NOT associated only with an app)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.release'),
            preserve_default=False,
        ),
    ]
