# Generated by Django 4.2.4 on 2024-12-03 15:22

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0005_assignation_ephemeral"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("DISCONNECT", "Disconnect (Agent disconnected)"),
                            ("CONNECT", "Connect (Agent connected)"),
                        ],
                        choices_enum=facade.enums.AgentEventChoices,
                        help_text="The event kind",
                        max_length=1000,
                    ),
                ),
                (
                    "level",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("DEBUG", "DEBUG Level"),
                            ("INFO", "INFO Level"),
                            ("ERROR", "ERROR Level"),
                            ("WARN", "WARN Level"),
                            ("CRITICAL", "CRITICAL Level"),
                        ],
                        choices_enum=facade.enums.LogLevelChoices,
                        help_text="The event level",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="facade.agent",
                    ),
                ),
            ],
        ),
    ]
