# Generated by Django 5.2 on 2025-11-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_assignation_catpure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignation',
            old_name='catpure',
            new_name='capture',
        ),
    ]
