# Generated by Django 6.0.3 on 2026-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_state_app_identifier_state_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='args_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical sha256 of the assign args (provenance canonicalization v1) — the replay-discovery key', max_length=64, null=True),
        ),
    ]
