# Generated by Django 5.2 on 2025-08-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_dependency_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignationevent',
            name='delegated_to',
            field=models.ForeignKey(blank=True, help_text='If this event was delegated to another assignation, which one?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_events', to='facade.assignation'),
        ),
    ]
