# Generated by Django 6.0.3 on 2026-05-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0005_implementation_manipulates_implementation_tracks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UICatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("schema", models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name="statemapping",
            name="materialized_blok",
        ),
        migrations.RemoveField(
            model_name="statemapping",
            name="state",
        ),
        migrations.RemoveField(
            model_name="blok",
            name="action_demands",
        ),
        migrations.RemoveField(
            model_name="blok",
            name="state_demands",
        ),
        migrations.RemoveField(
            model_name="blok",
            name="url",
        ),
        migrations.RemoveField(
            model_name="materializedblok",
            name="agent",
        ),
        migrations.AddField(
            model_name="blok",
            name="agent_dependencies",
            field=models.JSONField(default=list, help_text="The agent dependencies for this Blok"),
        ),
        migrations.AddField(
            model_name="blok",
            name="ui_schema",
            field=models.JSONField(default=dict, help_text="The UI schema for this Blok"),
        ),
        migrations.AddField(
            model_name="blok",
            name="uri",
            field=models.CharField(blank=True, help_text="The URI for this Blok (e.g. if it should be rendered as an iframe)", max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="BlokAgentMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="general", help_text="The reference of the dependency this mapping is for (e.g. imagej)", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_mappings", to="facade.agent")),
                ("materialized_blok", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_mappings", to="facade.materializedblok")),
            ],
        ),
        migrations.AddField(
            model_name="blok",
            name="catalog",
            field=models.ForeignKey(help_text="The catalog this Blok belongs to", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="bloks", to="facade.uicatalog"),
        ),
        migrations.DeleteModel(
            name="ActionMapping",
        ),
        migrations.DeleteModel(
            name="StateMapping",
        ),
        migrations.AddConstraint(
            model_name="blokagentmapping",
            constraint=models.UniqueConstraint(fields=("materialized_blok", "key"), name="unique_dependency_per_materialized_blok"),
        ),
    ]
