# Generated by Django 4.2.4 on 2024-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0005_rename_schema_state_state_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="stateschema",
            name="description",
            field=models.CharField(default="None", max_length=2000),
            preserve_default=False,
        ),
    ]
