# Generated by Django 5.2 on 2025-12-01 17:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_rename_catpure_assignation_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='acted_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, help_text='Which structures were acted on in this assignation', size=None),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='action',
            field=models.ForeignKey(help_text='The action this was assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.action'),
        ),
    ]
