# Generated by Django 4.2.4 on 2023-09-01 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0006_rename_reservation_provisionevent_provision"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="defined_at",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="provisionevent",
            name="provision",
            field=models.ForeignKey(
                help_text="The provision this log item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="facade.provision",
            ),
        ),
    ]
