# Generated by Django 6.0.3 on 2026-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_uicatalog_remove_statemapping_materialized_blok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='ui_schema',
        ),
        migrations.AddField(
            model_name='blok',
            name='components',
            field=models.JSONField(default=list, help_text='The UI schema for this Blok'),
        ),
    ]
