# Generated by Django 6.0.3 on 2026-07-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0006_task_args_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystemshelve',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='filesystemshelve',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='action',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='structure',
        ),
        migrations.DeleteModel(
            name='FileDrawer',
        ),
        migrations.DeleteModel(
            name='FilesystemShelve',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='IconPack',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
