# Generated by Django 5.2 on 2026-03-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0006_agent_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='device',
            field=models.ForeignKey(default=1, help_text='The device this agent belongs to (agents are part of a device and are NOT associated only with an app or release)', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authentikate.device'),
            preserve_default=False,
        ),
    ]
