# Generated by Django 4.2.4 on 2024-08-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0006_stateschema_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="reservations",
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="facade.structure",
            ),
        ),
        migrations.AlterField(
            model_name="stateschema",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_schemas",
                to="facade.agent",
            ),
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ui_id", models.CharField(max_length=2000)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="facade.dashboard",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="facade.reservation",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="facade.state",
                    ),
                ),
            ],
        ),
    ]
