# Generated by Django 6.0.3 on 2026-07-30 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('facade', '0007_remove_filesystemshelve_agents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='argport',
            name='compiled_jsonpath',
            field=models.TextField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', null=True),
        ),
        migrations.AlterField(
            model_name='returnport',
            name='compiled_jsonpath',
            field=models.TextField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', null=True),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['hash'], name='action_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['organization', 'key'], name='action_org_key_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['name'], name='action_name_idx'),
        ),
    ]
