# Generated by Django 4.2.4 on 2024-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0007_remove_dashboard_reservations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="name",
            field=models.CharField(default="My Dashboard", max_length=2000),
            preserve_default=False,
        ),
    ]
