# Generated by Django 5.2 on 2025-12-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_assignation_acted_on_alter_assignation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
