# Generated by Django 5.2 on 2026-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_agent_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='auto_resolvable',
            field=models.BooleanField(default=True, help_text='If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.'),
        ),
    ]
