# Generated by Django 6.0.3 on 2026-05-20 12:04

import django.db.models.deletion
import facade.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0007_remove_blok_ui_schema_blok_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlokDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(help_text='A reference for this dependency', max_length=2000)),
                ('action_demands', models.JSONField(default=list, help_text='The action demands this dependency has to meet')),
                ('auto_resolvable', models.BooleanField(default=False, help_text='If this dependency is auto resolvable, the system will try to automatically bind any agent that the user can assign to this dependency. If False, the user will have to manually bind an agent to this dependency before it can be used.')),
                ('app_filter', models.CharField(blank=True, help_text='If set, only Agents of this app will be able to be assigned to this dependency.', max_length=2000, null=True)),
                ('version_filter', models.CharField(blank=True, help_text='If set, only Agents of this version will be able to be assigned to this dependency', max_length=100, null=True)),
                ('optional', models.BooleanField(default=False, help_text='Is this dependency optional')),
                ('description', models.TextField(blank=True, help_text='A description for this dependency', null=True)),
                ('min_viable_instances', models.IntegerField(help_text='The minimal viable instance count for this dependency', null=True)),
                ('max_viable_instances', models.IntegerField(help_text='The maximal viable instance count for this dependency', null=True)),
                ('prefered_instances', models.IntegerField(help_text='The prefered instance count for this dependency', null=True)),
                ('assign_policy', models.CharField(choices=[(facade.enums.AssignPolicy['AUTOMATIC'], 'AUTOMATIC'), (facade.enums.AssignPolicy['ROUND_ROBIN'], 'ROUND_ROBIN'), (facade.enums.AssignPolicy['LEAST_BUSY'], 'LEAST_BUSY'), (facade.enums.AssignPolicy['FASTEST_RESPONSE'], 'FASTEST_RESPONSE')], default=facade.enums.AssignPolicy['AUTOMATIC'], help_text='The assign policy for this dependency', max_length=1000)),
                ('blok', models.ForeignKey(help_text='The implementation that has this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='facade.blok')),
            ],
        ),
    ]
