# Generated by Django 4.2.4 on 2023-11-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0008_provision_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provision",
            name="causing_reservation",
            field=models.ForeignKey(
                blank=True,
                help_text="Reservation that created this provision",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_provisions",
                to="facade.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="provision",
            name="template",
            field=models.OneToOneField(
                blank=True,
                help_text="The Template for this Provision",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provision",
                to="facade.template",
            ),
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="A reference for this dependency",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "optional",
                    models.BooleanField(
                        default=False,
                        help_text="Is this dependency optional (e.g. can we still use the template if this dependency is not met)",
                    ),
                ),
                (
                    "binds",
                    models.JSONField(
                        default=dict,
                        help_text="The binds for this dependency (Determines which templates can be used for this dependency)",
                        max_length=2000,
                    ),
                ),
                (
                    "viable_instances",
                    models.IntegerField(
                        default=1,
                        help_text="How many instances of this dependency do we need to be viable",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="The node this dependency is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="facade.node",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The Template that has this dependency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="facade.template",
                    ),
                ),
            ],
        ),
    ]
