# Generated by Django 6.0.3 on 2026-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_alter_argport_compiled_jsonpath_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='descriptor',
            name='No multiple Descriptors with same key in the same package allowed',
        ),
        migrations.RemoveField(
            model_name='historicalstate',
            name='state',
        ),
        migrations.RemoveConstraint(
            model_name='interface',
            name='No multiple Interfaces with same key in the same package allowed',
        ),
        migrations.RemoveConstraint(
            model_name='structure',
            name='No multiple Structures with same key in the same package allowed',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='action',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='action',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='dynamic',
        ),
        migrations.AlterField(
            model_name='lock',
            name='description',
            field=models.TextField(blank=True, help_text='A description for the Lock', null=True),
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='package',
        ),
        migrations.DeleteModel(
            name='HistoricalState',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='package',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='protocols',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='descriptors',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='implements',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='package',
        ),
        migrations.DeleteModel(
            name='Descriptor',
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.DeleteModel(
            name='StructurePackage',
        ),
    ]
