# Generated by Django 5.2 on 2025-12-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0008_assignation_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='action_hash',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='arg_matches',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='protocols',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='return_matches',
        ),
        migrations.AddField(
            model_name='dependency',
            name='action_demands',
            field=models.JSONField(default=list, help_text='The action demands this dependency has to meet'),
        ),
        migrations.CreateModel(
            name='ResolvedDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('dependency_key', models.CharField(help_text='The key of the dependency that was resolved (i.e the method of the agent protocol)', max_length=2000)),
                ('dependency', models.ForeignKey(help_text='The dependency that was resolved', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_dependencies', to='facade.dependency')),
                ('implementation', models.ForeignKey(help_text='The implementation that was used to resolve this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_dependencies', to='facade.implementation')),
                ('resolved_for', models.ForeignKey(help_text='The assignation that needed this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_dependencies', to='facade.assignation')),
            ],
        ),
    ]
