# Generated by Django 5.2 on 2026-03-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('facade', '0008_dependency_auto_resolvable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='app',
            field=models.ForeignKey(default=1, help_text='The app this dependency belongs to (dependencies are part of an app and are NOT associated only with a release)', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='authentikate.app'),
            preserve_default=False,
        ),
    ]
