# Generated by Django 5.2 on 2025-12-11 14:44

import django.utils.timezone
import facade.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_remove_dependency_action_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='assign_policy',
            field=models.CharField(choices=[(facade.enums.AssignPolicy['AUTOMATIC'], 'AUTOMATIC'), (facade.enums.AssignPolicy['ROUND_ROBIN'], 'ROUND_ROBIN'), (facade.enums.AssignPolicy['LEAST_BUSY'], 'LEAST_BUSY'), (facade.enums.AssignPolicy['FASTEST_RESPONSE'], 'FASTEST_RESPONSE')], default=facade.enums.AssignPolicy['AUTOMATIC'], help_text='The assign policy for this dependency', max_length=1000),
        ),
        migrations.AddField(
            model_name='dependency',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='description',
            field=models.TextField(blank=True, help_text='A description for this dependency', null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='minimal_viable_instances',
            field=models.IntegerField(default=1, help_text='The minimal viable instance count for this dependency'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='optional',
            field=models.BooleanField(default=False, help_text='Is this dependency optional'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='prefered_instances',
            field=models.IntegerField(default=1, help_text='The prefered instance count for this dependency'),
        ),
    ]
