# Generated by Django 6.0.3 on 2026-08-10 15:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_remove_descriptor_no_multiple_descriptors_with_same_key_in_the_same_package_allowed_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['agent', '-created_at'], name='task_agent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['latest_event_kind', '-created_at'], name='task_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acted_on'], name='task_acted_on_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('is_done', False), ('root__isnull', True)), fields=['caller', '-created_at'], name='task_my_root_open_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('ephemeral', False), ('is_done', True), ('latest_event_kind', 'COMPLETED')), fields=['args_hash', 'action', '-finished_at'], name='task_replay_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('is_done', False)), fields=['agent'], name='task_agent_open_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['caller', 'reference'], name='task_caller_ref_idx'),
        ),
    ]
