# Generated by Django 4.2.4 on 2024-08-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0009_panel_delete_control_dashboard_panels"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="accessors",
            field=models.JSONField(default=list),
        ),
    ]
