# Generated by Django 5.2 on 2026-03-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0009_dependency_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='action',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='app',
        ),
        migrations.AddField(
            model_name='dependency',
            name='implementation',
            field=models.ForeignKey(default=1, help_text='The implementation that has this dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='facade.implementation'),
            preserve_default=False,
        ),
    ]
