# Generated by Django 4.2.4 on 2024-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0009_alter_provision_causing_reservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="initial_hash",
            field=models.CharField(
                blank=True,
                help_text="The initial hash of the Node",
                max_length=1000,
                null=True,
            ),
        ),
    ]
