# Generated by Django 4.2.4 on 2024-04-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0010_dependency_initial_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="The node this dependency is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies",
                to="facade.node",
            ),
        ),
    ]
