# Generated by Django 5.2 on 2026-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_remove_dependency_action_remove_dependency_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='app_filter',
            field=models.CharField(blank=True, help_text='If set, only Agents of this app will be able to be assigned to this dependency.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='version_filter',
            field=models.CharField(blank=True, help_text='If set, only Agents of this version will be able to be assigned to this dependency', max_length=100, null=True),
        ),
    ]
