# Generated by Django 6.0.3 on 2026-05-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0010_remove_blok_agent_dependencies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blok",
            name="demo_state",
            field=models.JSONField(default=dict, help_text="The initial state for this Blok (to display in the ui a fake version)"),
        ),
    ]
