# Generated by Django 5.2 on 2025-12-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_dependency_assign_policy_dependency_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolveddependency',
            name='dependency_key',
        ),
        migrations.RemoveField(
            model_name='resolveddependency',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='resolveddependency',
            name='resolved_for',
        ),
        migrations.AddField(
            model_name='resolveddependency',
            name='key',
            field=models.CharField(default='ff', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolveddependency',
            name='dependency',
            field=models.ForeignKey(blank=True, help_text='The dependency this choice is fulfilling', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facade.dependency'),
        ),
        migrations.AlterField(
            model_name='resolveddependency',
            name='implementation',
            field=models.ForeignKey(help_text='The tool chosen to fulfill the dependency', on_delete=django.db.models.deletion.PROTECT, to='facade.implementation'),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, help_text="If set, this is a named preset (e.g. 'Standard Zeiss Config')", max_length=200, null=True)),
                ('is_template', models.BooleanField(default=False, help_text='If True, this resolution appears in search results for other users to reuse.')),
                ('implementation', models.ForeignKey(help_text='The specific Implementation that this tree is configuring dependencies for.', on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='facade.implementation')),
            ],
        ),
        migrations.AddField(
            model_name='resolveddependency',
            name='down_stream_resolution',
            field=models.ForeignKey(blank=True, help_text="The configuration tree for THIS implementation's dependencies", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='facade.resolution'),
        ),
        migrations.AddField(
            model_name='resolveddependency',
            name='resolution',
            field=models.ForeignKey(default=1, help_text='The resolution scope this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_dependencies', to='facade.resolution'),
            preserve_default=False,
        ),
    ]
