# Generated by Django 6.0.3 on 2026-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0010_task_task_agent_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='lease_epoch',
            field=models.BigIntegerField(default=0, help_text="Monotonic fencing token for the executor write-lease. Bumped on every claim (connect) and on every revoke (stale sweep). A connection carries the epoch it claimed and renews its lease with a compare-and-set on it, so a displaced or revoked connection's heartbeat matches no row and the connection terminates itself. Distinct from active_connection_id (a socket *name*, unique but not revocable) and active_session_id (the client-supplied *process* identity, which must stay equal across a reclaiming reconnect)."),
        ),
    ]
