# Generated by Django 4.2.4 on 2025-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0010_shortcut_allow_quick_alter_shortcut_args_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcut",
            name="use_returns",
            field=models.BooleanField(
                default=False,
                help_text="Use the result of this Shortcut (e.g. use the result in the next Shortcut)",
            ),
        ),
    ]
