# Generated by Django 4.2.4 on 2024-08-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0010_panel_accessors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panel",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="facade.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="facade.state",
            ),
        ),
    ]
