# Generated by Django 5.2 on 2025-12-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0011_remove_resolveddependency_dependency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='resolution',
            field=models.ForeignKey(blank=True, help_text='The resolution used for this assignation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='facade.resolution'),
        ),
    ]
