# Generated by Django 6.0.3 on 2026-08-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0011_agent_lease_epoch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='originating_connection_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='originating_session_id',
        ),
    ]
