# Generated by Django 6.0.3 on 2026-03-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0011_dependency_app_filter_dependency_version_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('key', models.CharField(help_text='A unique identifier for this lock within the agent', max_length=2000)),
                ('extension', models.CharField(default='general', help_text="The extension this lock is for (e.g. 'imagej')", max_length=2000)),
                ('description', models.TextField(help_text='A description for the Lock')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent this lock belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='facade.agent')),
                ('hold_by', models.ForeignKey(blank=True, help_text='The assigniation that currently holds this lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_locks', to='facade.assignation')),
            ],
        ),
    ]
