# Generated by Django 4.2.4 on 2024-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0011_alter_panel_reservation_alter_panel_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="ui_tree",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
