# Generated by Django 6.0.3 on 2026-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0012_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hash',
            field=models.CharField(default=1, help_text='The hash of the Agent (comparing the hash can be used to check if the agent has changed in a definition way)', max_length=1000),
            preserve_default=False,
        ),
    ]
