# Generated by Django 5.2 on 2025-12-11 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0004_device_client_device'),
        ('facade', '0012_assignation_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='creator',
            field=models.ForeignKey(default=1, help_text='The user that created this Resolution', on_delete=django.db.models.deletion.CASCADE, related_name='created_resolutions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolution',
            name='organization',
            field=models.ForeignKey(default=1, help_text='The organization this Resolution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='authentikate.organization'),
            preserve_default=False,
        ),
    ]
