# Generated by Django 6.0.3 on 2026-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0012_remove_task_originating_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_higher_order_child',
            field=models.BooleanField(default=False, help_text='Whether this task is the lower child of a higher-order wrapper — its yields/terminals unfold onto the wrapper. Lets the event hot path skip the parent lookup for ordinary tasks.'),
        ),
    ]
