# Generated by Django 4.2.4 on 2024-04-30 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0012_alter_dependency_binds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dependency",
            name="viable_instances",
        ),
    ]
