# Generated by Django 4.2.4 on 2024-08-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0012_alter_dashboard_ui_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="facade.template",
            ),
        ),
    ]
