# Generated by Django 5.2 on 2025-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0013_resolution_creator_resolution_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolveddependency',
            name='resolution_key',
            field=models.CharField(blank=True, help_text='An optional key to identify this resolution in the context of its parent resolution', max_length=2000, null=True),
        ),
    ]
