# Generated by Django 4.2.4 on 2024-04-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0013_remove_dependency_viable_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="causing_dependency",
            field=models.ForeignKey(
                blank=True,
                help_text="Was this Reservation caused by a Dependency?",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caused_reservations",
                to="facade.dependency",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="The node this dependency is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependees",
                to="facade.node",
            ),
        ),
    ]
