# Generated by Django 6.0.3 on 2026-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0013_agent_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='dependency',
            field=models.CharField(blank=True, default='general', help_text='The reference of the dependency this assignation was assigned to (e.g. imagej)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignation',
            name='dependency_method',
            field=models.CharField(blank=True, help_text='The action of the dependency this assignation was assigned to (e.g. imagej.fft )', max_length=1000, null=True),
        ),
    ]
