# Generated by Django 4.2.4 on 2024-08-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0013_panel_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                help_text="This Reservations app",
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="facade.waiter",
            ),
        ),
    ]
