# Generated by Django 6.0.3 on 2026-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0013_task_is_higher_order_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='allow_probe',
            field=models.BooleanField(default=False, help_text='May this action be invoked as a probe (zero persistence, no history/replay/recovery)? Declared by the action author; the probe mutation refuses actions without it.'),
        ),
    ]
