# Generated by Django 5.2 on 2026-03-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_resolveddependency_resolution_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(help_text='The operation of this patch (e.g. add, remove, replace)', max_length=1000)),
                ('path', models.CharField(help_text='The path of this patch (e.g. the path to the value that is being changed)', max_length=1000)),
                ('value', models.JSONField(help_text='The value of this patch (e.g. the new value that is being set)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time this patch was created')),
                ('current_revision', models.IntegerField(help_text='The current revision of the state after applying this patch')),
                ('future_revision', models.IntegerField(help_text='The number of future revisions that have been applied after this patch (e.g. if this patch is in the middle of the log, there might be future patches that have been applied after it)')),
                ('global_current_revision', models.IntegerField(help_text='The current revision of the state in the global context (e.g. considering all patches that have been applied to this state)')),
                ('global_future_revision', models.IntegerField(help_text='The number of future revisions that have been applied after this patch in the global context (e.g. if this patch is in the middle of')),
                ('session_id', models.CharField(help_text='The session id of the user that made this change (e.g. to be able to track changes by user)', max_length=1000)),
                ('assignation_id', models.ForeignKey(blank=True, help_text='The assignation that caused this patch (e.g. to be able to track changes by assignation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.assignation')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.state')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(help_text='The value of this snapshot (e.g. the value of the state at the time of the snapshot)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time this snapshot was created')),
                ('revision', models.IntegerField(help_text='The revision of the state at the time of the snapshot (e.g. to be able to reconstruct the state at this point in time)')),
                ('session_id', models.CharField(help_text='The session id of the user that made this snapshot (e.g. to be able to track snapshots by user)', max_length=1000)),
                ('global_revision', models.IntegerField(help_text='The revision of the state in the global context at the time of the snapshot (e.g. considering all patches that have been applied to this state)')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='facade.state')),
            ],
        ),
    ]
