# Generated by Django 4.2.4 on 2024-08-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0014_alter_reservation_waiter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panel",
            name="accessors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                help_text="Which Waiter created this Reservation (if any?)",
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="facade.waiter",
            ),
        ),
    ]
