# Generated by Django 6.0.3 on 2026-08-19 11:39

from django.db import migrations, models


def backfill_task_roots(apps, schema_editor):
    """Backfill ``Task.root`` for rows created before root propagation existed.

    Level-by-level: each pass resolves children whose parent's root is already known
    (or whose parent IS a root). Iterations are bounded by the deepest task chain.
    """
    with schema_editor.connection.cursor() as cursor:
        while True:
            cursor.execute(
                """
                UPDATE facade_task c SET root_id = COALESCE(p.root_id, p.id)
                FROM facade_task p
                WHERE c.parent_id = p.id AND c.root_id IS NULL
                  AND (p.root_id IS NOT NULL OR p.parent_id IS NULL)
                """
            )
            if cursor.rowcount == 0:
                break


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0014_action_allow_probe'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('is_done', True), ('root__isnull', True)), fields=['finished_at'], name='task_retention_idx'),
        ),
        migrations.RunPython(backfill_task_roots, migrations.RunPython.noop),
    ]
