# Generated by Django 6.0.3 on 2026-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0014_state_retention_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="logo",
            field=models.CharField(blank=True, help_text="An optional icon identifier to represent this Action in the UI (e.g. 'fa-solid fa-dog')", max_length=1000, null=True),
        ),
    ]
