# Generated by Django 4.2.4 on 2024-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0015_alter_panel_accessors_alter_reservation_waiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="name",
            field=models.CharField(default="Unnamed", max_length=2000),
        ),
    ]
