# Generated by Django 5.2 on 2026-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0015_patch_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='assignation_id',
            new_name='assignation',
        ),
    ]
