# Generated by Django 6.0.3 on 2026-08-19 13:32

import django_choices_field.fields
import facade.enums.log
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0015_task_task_retention_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='level',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('DEBUG', 'DEBUG Level'), ('INFO', 'INFO Level'), ('ERROR', 'ERROR Level'), ('WARN', 'WARN Level'), ('CRITICAL', 'CRITICAL Level')], choices_enum=facade.enums.log.LogLevelChoices, help_text='The log level (LOG events)', max_length=1000, null=True),
        ),
    ]
