# Generated by Django 6.0.3 on 2026-03-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0012_alter_datalayerstore_path'),
        ('facade', '0015_space_spacemembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacemembership',
            name='agent',
        ),
        migrations.CreateModel(
            name='AgentScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_function', models.CharField(help_text='The function used to transfer the state of the model to properties of the scence', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent this scene belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='facade.agent')),
            ],
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='agent_scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to='facade.agentscene'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(help_text='The media file containing this 3D model', on_delete=django.db.models.deletion.CASCADE, related_name='threedmodels', to='datalayer.mediastore')),
            ],
        ),
        migrations.AddField(
            model_name='agentscene',
            name='model',
            field=models.ForeignKey(help_text='The 3D model used for this scene', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='facade.threedmodel'),
        ),
    ]
