# Generated by Django 4.2.4 on 2024-05-03 10:14

from django.db import migrations
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0016_provision_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="strategy",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    (
                        "RANDOM",
                        "Random (Assignation is assigned to a random Provision)",
                    ),
                    (
                        "ROUND_ROBIN",
                        "Round Robin (Assignation is assigned to the next Provision)",
                    ),
                    (
                        "LEAST_BUSY",
                        "Least Busy (Assignation is assigned to the least busy Provision)",
                    ),
                    (
                        "LEAST_TIME",
                        "Least Time (Assignation is assigned to the Provision with the least time left)",
                    ),
                    (
                        "LEAST_LOAD",
                        "Least Load (Assignation is assigned to the Provision with the least load)",
                    ),
                ],
                choices_enum=facade.enums.ReservationStrategyChoices,
                default="RANDOM",
                help_text="The Strategy of this Reservation",
                max_length=1000,
            ),
        ),
    ]
