# Generated by Django 6.0.3 on 2026-03-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0016_remove_spacemembership_agent_agentscene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='arg_count',
            field=models.IntegerField(default=0, help_text='Pre-calculated number of root input ports'),
        ),
        migrations.AddField(
            model_name='action',
            name='return_count',
            field=models.IntegerField(default=0, help_text='Pre-calculated number of root output ports'),
        ),
        migrations.CreateModel(
            name='ArgPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The position of this port in the list')),
                ('key', models.CharField(help_text="The local key (e.g. 'mask')", max_length=255, null=True)),
                ('key_path', models.CharField(db_index=True, help_text="The full dot-notation path (e.g. 'options.advanced.mask')", max_length=500)),
                ('kind', models.CharField(help_text='The structural kind (e.g. LIST, DICT, INT)', max_length=50, null=True)),
                ('identifier', models.CharField(db_index=True, help_text="The macro-type (e.g. '@mikro/image')", max_length=255, null=True)),
                ('compiled_jsonpath', models.CharField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', max_length=1000, null=True)),
                ('nullable', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arg_ports', to='facade.action')),
                ('parent', models.ForeignKey(blank=True, help_text='If this port is nested inside a LIST or DICT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.argport')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['action', 'key_path'], name='facade_argp_action__95bf79_idx'), models.Index(fields=['identifier'], name='facade_argp_identif_b280d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReturnPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The position of this port in the list')),
                ('key', models.CharField(help_text="The local key (e.g. 'mask')", max_length=255, null=True)),
                ('key_path', models.CharField(db_index=True, help_text="The full dot-notation path (e.g. 'options.advanced.mask')", max_length=500)),
                ('kind', models.CharField(help_text='The structural kind (e.g. LIST, DICT, INT)', max_length=50, null=True)),
                ('identifier', models.CharField(db_index=True, help_text="The macro-type (e.g. '@mikro/image')", max_length=255, null=True)),
                ('compiled_jsonpath', models.CharField(blank=True, help_text='PostgreSQL JSONPath string for micro-constraints', max_length=1000, null=True)),
                ('nullable', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_ports', to='facade.action')),
                ('parent', models.ForeignKey(blank=True, help_text='If this port is nested inside a LIST or DICT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.returnport')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['action', 'key_path'], name='facade_retu_action__8a4c86_idx'), models.Index(fields=['identifier'], name='facade_retu_identif_3e34f8_idx')],
            },
        ),
    ]
