# Generated by Django 4.2.4 on 2024-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0016_panel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="stateful",
            field=models.BooleanField(
                default=False,
                help_text="Is this function stateful. e.g does it inherently depend on or change state (think physical devices)?",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="idempotent",
            field=models.BooleanField(
                default=False,
                help_text="Is this function idempotent. e.g can we run it multiple times without ?",
            ),
        ),
    ]
