# Generated by Django 6.0.3 on 2026-04-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0017_action_arg_count_action_return_count_argport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='global_current_revision',
            new_name='global_rev',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='current_revision',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='future_revision',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='global_future_revision',
        ),
    ]
