# Generated by Django 4.2.4 on 2024-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0017_node_stateful_alter_node_idempotent"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="submit_on_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="panel",
            name="submit_on_load",
            field=models.BooleanField(default=False),
        ),
    ]
