# Generated by Django 4.2.4 on 2024-05-03 11:45

from django.db import migrations, models
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0017_reservation_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignation",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("QUEUED", "Queued (Assignation was queued for a reservation)"),
                    ("BOUND", "Bound (Assignation was bound to an Agent)"),
                    ("ASSIGN", "Assign (Agent accepted the Assignation)"),
                    ("UNASSIGN", "Unassign (Agent received the Assignation)"),
                    (
                        "PROGRESS",
                        "Progress (Agent is making progress on the Assignation)",
                    ),
                    (
                        "CANCELING",
                        "Unassign (Assignation was unassigned from an Agent)",
                    ),
                    (
                        "CANCELLED",
                        "Unassign (Assignation was unassigned from an Agent)",
                    ),
                    ("INTERUPTING", "Interupting (Assignation was interupted)"),
                    ("INTERUPTED", "Interupted (Assignation was interupted)"),
                    ("YIELD", "Yields (Agent yielded the result)"),
                    ("DONE", "Done (Agent finished the Assignation)"),
                    ("LOG", "Log (Agent logged a message)"),
                ],
                choices_enum=facade.enums.AssignationEventChoices,
                help_text="The latest Status of this Provision (transitioned by events)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="assignationevent",
            name="progress",
            field=models.IntegerField(
                blank=True, help_text="The progress of the assignation", null=True
            ),
        ),
    ]
