# Generated by Django 6.0.3 on 2026-06-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0018_backfill_relational_ports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='extensions',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='extension',
        ),
    ]
