# Generated by Django 6.0.3 on 2026-04-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0018_rename_global_current_revision_patch_global_rev_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='global_revision',
            new_name='global_rev',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='revision',
        ),
    ]
