# Generated by Django 6.0.3 on 2026-06-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0019_remove_agent_extensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementation',
            name='extensions',
        ),
    ]
