# Generated by Django 4.2.4 on 2024-05-06 13:53

from django.db import migrations
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0019_provision_dependencies_met_provision_provided_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignationevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                default="DEBUG",
                help_text="The event level",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provisionevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                default="DEBUG",
                help_text="The event level",
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                default="DEBUG",
                help_text="The event level",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
