# Generated by Django 4.2.4 on 2024-05-06 13:55

from django.db import migrations
import django_choices_field.fields
import facade.enums


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0020_assignationevent_level_provisionevent_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignationevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                help_text="The event level",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="provisionevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                help_text="The event level",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationevent",
            name="level",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("DEBUG", "DEBUG Level"),
                    ("INFO", "INFO Level"),
                    ("ERROR", "ERROR Level"),
                    ("WARN", "WARN Level"),
                    ("CRITICAL", "CRITICAL Level"),
                ],
                choices_enum=facade.enums.LogLevelChoices,
                help_text="The event level",
                max_length=1000,
                null=True,
            ),
        ),
    ]
