# Generated by Django 6.0.3 on 2026-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0022_remove_caller_no_multiple_registries_for_same_app_and_user_in_the_same_organization_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="needs_token",
            field=models.BooleanField(default=True, help_text="Whether Rekuest mints a signed provenance token when this implementation is assigned. Default true (provenance-by-default); false skips minting for trivial/internal tasks."),
        ),
        migrations.AddField(
            model_name="implementation",
            name="provenance_audience",
            field=models.JSONField(blank=True, help_text="Optional declared audience (list of downstream service names) for the provenance token's `aud`. If null, the audience is derived at dispatch from the structures the assignment acts on.", null=True),
        ),
    ]
