# Generated by Django 4.2.4 on 2024-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0023_agent_connected_agent_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="last_seen",
            field=models.DateTimeField(
                help_text="The last time this Agent was seen", null=True
            ),
        ),
    ]
