# Generated by Django 6.0.3 on 2026-06-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0024_remove_assignation_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='device',
        ),
    ]
