# Generated by Django 6.0.3 on 2026-06-21 12:17

import rekuest_core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0025_remove_agent_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blokdependency",
            name="assign_policy",
            field=models.CharField(
                choices=[
                    (rekuest_core.enums.AssignPolicy["AUTOMATIC"], "AUTOMATIC"),
                    (rekuest_core.enums.AssignPolicy["BALANCED"], "BALANCED"),
                    (rekuest_core.enums.AssignPolicy["ROUND_ROBIN"], "ROUND_ROBIN"),
                    (rekuest_core.enums.AssignPolicy["LEAST_BUSY"], "LEAST_BUSY"),
                    (rekuest_core.enums.AssignPolicy["FASTEST_RESPONSE"], "FASTEST_RESPONSE"),
                ],
                default=rekuest_core.enums.AssignPolicy["AUTOMATIC"],
                help_text="The assign policy for this dependency",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="assign_policy",
            field=models.CharField(
                choices=[
                    (rekuest_core.enums.AssignPolicy["AUTOMATIC"], "AUTOMATIC"),
                    (rekuest_core.enums.AssignPolicy["BALANCED"], "BALANCED"),
                    (rekuest_core.enums.AssignPolicy["ROUND_ROBIN"], "ROUND_ROBIN"),
                    (rekuest_core.enums.AssignPolicy["LEAST_BUSY"], "LEAST_BUSY"),
                    (rekuest_core.enums.AssignPolicy["FASTEST_RESPONSE"], "FASTEST_RESPONSE"),
                ],
                default=rekuest_core.enums.AssignPolicy["AUTOMATIC"],
                help_text="The assign policy for this dependency",
                max_length=1000,
            ),
        ),
    ]
