# Generated by Django 4.2.4 on 2024-06-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0026_iconpack_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignation",
            name="node",
            field=models.ForeignKey(
                default=1,
                help_text="The node this was assigned to",
                on_delete=django.db.models.deletion.CASCADE,
                to="facade.node",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignation",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Which tempalten are we assigning to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignations",
                to="facade.template",
            ),
        ),
    ]
