# Generated by Django 6.0.3 on 2026-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0027_implementation_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='originating_connection_id',
            field=models.CharField(blank=True, help_text="The websocket connection id that originated this (root) assignation over the agent socket. Identifies which live connection's death should cascade-cancel it. Null for GraphQL-originated or non-root assignations.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignation',
            name='originating_session_id',
            field=models.CharField(blank=True, help_text="The caller's process session id (volatile, in-memory) at origination. Lets a reconnect with the same session reclaim instead of cascade-cancelling. Null for GraphQL-originated or non-root assignations.", max_length=1000, null=True),
        ),
    ]
