# Generated by Django 4.2.4 on 2024-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0027_assignation_node_assignation_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_dev",
            field=models.BooleanField(
                default=False, help_text="Is this Node a development Node"
            ),
        ),
    ]
