# Generated by Django 6.0.3 on 2026-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0028_assignation_originating_connection_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="active_session_id",
            field=models.CharField(
                blank=True,
                help_text="The executor process's volatile session id from the last connect. On reconnect, a matching session means the same process survived (reclaim in-flight work); a different session means a fresh process (fail-and-cascade the orphaned work).",
                max_length=1000,
                null=True,
            ),
        ),
    ]
