# Generated by Django 4.2.4 on 2024-07-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facade", "0029_agent_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="causing_assignation",
            field=models.ForeignKey(
                blank=True,
                help_text="The assignation that created this reservation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caused_reservations",
                to="facade.assignation",
            ),
        ),
    ]
