# Generated by Django 6.0.3 on 2026-06-23 12:00

import django.contrib.postgres.fields
import django.db.models.deletion
import django_choices_field.fields
import facade.enums.action
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0031_rename_assignation_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='dynamic',
            field=models.BooleanField(help_text='Dynamic Implementations will be able to create new tasks on runtime'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='effect',
            field=django_choices_field.fields.TextChoicesField(choices=[('NONE', 'None (no real-world effect; freely retryable)'), ('PHYSICAL', 'Physical (touches the real world; ambiguous failure is terminal)')], choices_enum=facade.enums.action.EffectClassChoices, default='NONE', help_text='The effect class of this implementation. NONE work is freely retryable/reclaimable; PHYSICAL work touches the real world and an ambiguous failure is terminal. Declared by the implementation, read at dispatch from task.implementation.effect — never caller-supplied.', max_length=8),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='tracks',
            field=models.JSONField(default=list, help_text='A log of all the tasks that have been provisioned with this implementation, as well as their status and results'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task that caused this patch (e.g. to be able to track changes by task)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='facade.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='acted_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, help_text='Which structures were acted on in this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.ForeignKey(help_text='The action this was assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facade.action'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(help_text='This Task app', max_length=1000, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facade.agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='caller',
            field=models.ForeignKey(blank=True, help_text='The caller (client/user/organization) that created this Task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facade.caller'),
        ),
        migrations.AlterField(
            model_name='task',
            name='capture',
            field=models.BooleanField(default=False, help_text='Should we capture the logs and events of this Task (e.g. for debugging or auditing purposes)?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependency',
            field=models.CharField(blank=True, default='general', help_text='The reference of the dependency this task was assigned to (e.g. imagej)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependency_method',
            field=models.CharField(blank=True, help_text='The action of the dependency this task was assigned to (e.g. imagej.fft )', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ephemeral',
            field=models.BooleanField(default=False, help_text='Is this Task ephemeral (e.g. should it be deleted after its done or should it be kept for future reference)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hooks',
            field=models.JSONField(default=list, help_text='hooks that are tight to the lifecycle of this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='implementation',
            field=models.ForeignKey(blank=True, help_text='Which implementation is the task currently mapped (can be reassigned)?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facade.implementation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Is this Task done (e.g. has it been completed and resulted in an error?)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='originating_connection_id',
            field=models.CharField(blank=True, help_text="The websocket connection id that originated this (root) task over the agent socket. Identifies which live connection's death should cascade-cancel it. Null for GraphQL-originated or non-root tasks.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='originating_session_id',
            field=models.CharField(blank=True, help_text="The caller's process session id (volatile, in-memory) at origination. Lets a reconnect with the same session reclaim instead of cascade-cancelling. Null for GraphQL-originated or non-root tasks.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The Tasks parent (the one that created this (none if there is no parent))', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='facade.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reference',
            field=models.CharField(default=uuid.uuid4, help_text='The Unique identifier of this Task considering its parent', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolution',
            field=models.ForeignKey(blank=True, help_text='The resolution used for this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facade.resolution'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='delegated_to',
            field=models.ForeignKey(blank=True, help_text='If this event was delegated to another task, which one?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_events', to='facade.task'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='progress',
            field=models.IntegerField(blank=True, help_text='The progress of the task (0-100) (set for yield events)', null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='task',
            field=models.ForeignKey(help_text='The task this log item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facade.task'),
        ),
        migrations.AlterField(
            model_name='taskinstruct',
            name='caller',
            field=models.ForeignKey(blank=True, help_text='Which caller created this Instruction (if any?)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instructs', to='facade.caller'),
        ),
        migrations.AlterField(
            model_name='taskinstruct',
            name='task',
            field=models.ForeignKey(help_text='The task this log item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='instructs', to='facade.task'),
        ),
    ]
