# Generated by Django 6.0.3 on 2026-04-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalayerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='The object-store URI of the file', max_length=1000, null=True, unique=True)),
                ('key', models.CharField(help_text='The object key/path within the datalayer bucket.', max_length=1000)),
                ('bucket', models.CharField(help_text='The datalayer bucket/service this store belongs to.', max_length=1000)),
                ('original_file_name', models.CharField(blank=True, help_text='The original client-provided file name.', max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The client-provided content type for the uploaded file.', max_length=255, null=True)),
                ('populated', models.BooleanField(default=False, help_text='Whether the store has been populated with a valid path and is ready for use.')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigFileStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='MediaStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ParquetStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ZarrStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('shape', models.JSONField(blank=True, help_text='The shape of the Zarr array stored at this location.', null=True)),
                ('chunks', models.JSONField(blank=True, help_text='The chunk size of the Zarr array stored at this location.', null=True)),
                ('version', models.CharField(blank=True, help_text='The Zarr format version of the array stored at this location.', max_length=10, null=True)),
                ('dtype', models.CharField(blank=True, help_text='The dtype of the Zarr array stored at this location.', max_length=255, null=True)),
                ('dimension_names', models.JSONField(blank=True, help_text='The dimension names declared by the Zarr array.', null=True)),
                ('fill_value', models.JSONField(blank=True, help_text='The fill value declared by the Zarr array.', null=True)),
                ('attributes', models.JSONField(blank=True, help_text='The user attributes stored in zarr.json.', null=True)),
                ('storage_transformers', models.JSONField(blank=True, help_text='The storage transformers declared by the Zarr array.', null=True)),
                ('chunk_key_encoding', models.JSONField(blank=True, help_text='The chunk key encoding configuration for the Zarr array.', null=True)),
                ('codecs', models.JSONField(blank=True, help_text='The codec pipeline declared for the Zarr array.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
    ]
