# Generated by Django 5.2 on 2026-04-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigfilestore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='datalayerstore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mediastore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='parquetstore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='zarrstore',
            options={'base_manager_name': 'objects'},
        ),
    ]
