# Generated by GitHub Copilot on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZarrStore",
            fields=[
                (
                    "datalayerstore_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="datalayer.datalayerstore",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("datalayer.datalayerstore",),
        ),
    ]