# Generated by GitHub Copilot on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0002_zarrstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayerstore",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="The client-provided content type for the uploaded file.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datalayerstore",
            name="original_file_name",
            field=models.CharField(
                blank=True,
                help_text="The original client-provided file name.",
                max_length=1000,
                null=True,
            ),
        ),
    ]