# Generated by Django 6.0.3 on 2026-05-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0002_alter_bigfilestore_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigfilestore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datalayerstore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediastore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parquetstore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zarrstore',
            options={},
        ),
    ]
