# Generated by Django 5.2 on 2026-03-16 13:57

import datalayer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0003_datalayerstore_upload_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalayerstore",
            name="bucket",
            field=models.CharField(
                help_text="The datalayer bucket/service this store belongs to.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="datalayerstore",
            name="key",
            field=models.CharField(
                help_text="The object key/path within the datalayer bucket.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="datalayerstore",
            name="path",
            field=datalayer.fields.StorePathField(
                blank=True,
                help_text="The object-store URI of the file",
                max_length=500,
                null=True,
                unique=True,
                validators=[
                    datalayer.fields.validate_store_path,
                    datalayer.fields.validate_store_path,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="datalayerstore",
            name="populated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the store has been populated with a valid path and is ready for use.",
            ),
        ),
    ]
