# Generated by Django 5.2 on 2026-03-16 14:24

import datalayer.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0005_alter_datalayerstore_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParquetStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.AlterModelOptions(
            name='bigfilestore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datalayerstore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediastore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zarrstore',
            options={},
        ),
        migrations.AlterField(
            model_name='datalayerstore',
            name='path',
            field=datalayer.fields.StorePathField(blank=True, help_text='The object-store URI of the file', max_length=500, null=True, unique=True, validators=[datalayer.fields.validate_store_path, datalayer.fields.validate_store_path]),
        ),
    ]
