# Generated by Django 5.2 on 2026-03-16 17:00

import datalayer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0006_parquetstore_alter_bigfilestore_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zarrstore",
            name="chunks",
            field=models.JSONField(
                blank=True,
                help_text="The chunk size of the Zarr array stored at this location.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="shape",
            field=models.JSONField(
                blank=True,
                help_text="The shape of the Zarr array stored at this location.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="The Zarr format version of the array stored at this location.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datalayerstore",
            name="path",
            field=datalayer.fields.StorePathField(
                blank=True,
                help_text="The object-store URI of the file",
                max_length=500,
                null=True,
                unique=True,
                validators=[
                    datalayer.fields.validate_store_path,
                    datalayer.fields.validate_store_path,
                ],
            ),
        ),
    ]
