# Generated by Django 5.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0007_zarrstore_chunks_zarrstore_shape_zarrstore_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zarrstore",
            name="attributes",
            field=models.JSONField(blank=True, help_text="The user attributes stored in zarr.json.", null=True),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="chunk_key_encoding",
            field=models.JSONField(blank=True, help_text="The chunk key encoding configuration for the Zarr array.", null=True),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="codecs",
            field=models.JSONField(blank=True, help_text="The codec pipeline declared for the Zarr array.", null=True),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="dimension_names",
            field=models.JSONField(blank=True, help_text="The dimension names declared by the Zarr array.", null=True),
        ),
        migrations.AddField(
            model_name="zarrstore",
            name="fill_value",
            field=models.JSONField(blank=True, help_text="The fill value declared by the Zarr array.", null=True),
        ),
    ]