# Generated by Django 5.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0008_zarrstore_additional_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="zarrstore",
            name="storage_transformers",
            field=models.JSONField(
                blank=True,
                help_text="The storage transformers declared by the Zarr array.",
                null=True,
            ),
        ),
    ]