# Generated by Django 5.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalayer", "0009_zarrstore_storage_transformers"),
    ]

    operations = [
        migrations.AddField(
            model_name="zarrstore",
            name="dtype",
            field=models.CharField(
                blank=True,
                help_text="The dtype of the Zarr array stored at this location.",
                max_length=255,
                null=True,
            ),
        ),
    ]