# Generated by Django 6.0.3 on 2026-03-23 16:55

import datalayer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0011_alter_datalayerstore_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayerstore',
            name='path',
            field=datalayer.fields.StorePathField(blank=True, help_text='The object-store URI of the file', max_length=500, null=True, unique=True, validators=[datalayer.fields.validate_store_path, datalayer.fields.validate_store_path]),
        ),
    ]
